using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client._Goobstation.UserInterface.Controls;

/// <summary>
/// A radial menu that automatically paginates items into pages of 5 items each.
/// Only shows "Next" button - use center button to go back or close.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class PaginatedRadialMenu : RadialMenu
{
    private const int ItemsPerPage = 5;

    public PaginatedRadialMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public new void SetButtons(IEnumerable<RadialMenuOption> models, SimpleRadialMenuSettings? settings = null)
    {
        ClearExistingChildrenRadialButtons();

        var sprites = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        var settingsToUse = settings ?? new SimpleRadialMenuSettings();
        
        var optionsList = models.ToList();

        // If list is small enough, use standard behavior (no pagination)
        if (optionsList.Count <= ItemsPerPage)
        {
            var rootContainer = new RadialContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                InitialRadius = settingsToUse.DefaultContainerRadius,
                ReserveSpaceForHiddenChildren = false,
                Visible = true
            };
            Children.Add(rootContainer);

            foreach (var model in optionsList)
            {
                var button = ConvertToButton(model, sprites, settingsToUse);
                rootContainer.AddChild(button);
            }
            return;
        }

        // Pagination: Split into pages
        var pages = new List<List<RadialMenuOption>>();
        for (var i = 0; i < optionsList.Count; i += ItemsPerPage)
        {
            pages.Add(optionsList.GetRange(i, Math.Min(ItemsPerPage, optionsList.Count - i)));
        }

        var pageContainers = new List<RadialContainer>();

        // Create all page containers
        for (var i = 0; i < pages.Count; i++)
        {
            var container = new RadialContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                InitialRadius = settingsToUse.DefaultContainerRadius,
                ReserveSpaceForHiddenChildren = false,
                Visible = i == 0 // Only first page visible
            };
            Children.Add(container);
            pageContainers.Add(container);
        }

        // Populate each page
        for (var i = 0; i < pages.Count; i++)
        {
            var container = pageContainers[i];
            var pageOptions = pages[i];
            var isLastPage = i == pages.Count - 1;

            // Add items for this page
            foreach (var model in pageOptions)
            {
                var button = ConvertToButton(model, sprites, settingsToUse);
                container.AddChild(button);
            }

            // Add "Next" button (except on last page)
            if (!isLastPage)
            {
                var nextContainer = pageContainers[i + 1];
                var nextButton = CreateNavigationButton(
                    Loc.GetString("ui-radial-menu-next-page"),
                    new ResPath("/Textures/Interface/Default/filled_right_arrow.svg.192dpi.png"),
                    settingsToUse,
                    sprites
                );
                nextButton.TargetLayer = nextContainer;
                container.AddChild(nextButton);
            }
        }
    }

    private RadialMenuTextureButton ConvertToButton(
        RadialMenuOption model,
        SpriteSystem sprites,
        SimpleRadialMenuSettings settings)
    {
        var button = settings.UseSectors
            ? new RadialMenuTextureButtonWithSector
            {
                DrawBorder = settings.DisplayBorders,
                DrawBackground = !settings.NoBackground
            }
            : new RadialMenuTextureButton();

        // Standard size 64x64
        button.SetSize = new Vector2(64f, 64f);
        button.ToolTip = model.ToolTip;

        // Screen Saver specific handling: 2x size (128x128) + Composite Sprite
        if (model is RadialMenuScreenSaverOption ssOption)
        {
            button.SetSize = new Vector2(128f, 128f);
            
            // Add Head Sprite
            if (ssOption.HeadSprite != null)
            {
                var texture = sprites.Frame0(ssOption.HeadSprite);
                var textureRect = new TextureRect
                {
                    Texture = texture,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    SetSize = new Vector2(128f, 128f), // Fill button
                    MouseFilter = MouseFilterMode.Ignore,
                    Modulate = ssOption.HeadColor ?? Color.White,
                    Margin = new Thickness(0, 50, 0, 0) // Shift down heavily (2x previous)
                };
                button.AddChild(textureRect);
            }

            // Add Screen Sprite (Overlay)
            if (ssOption.ScreenSprite != null)
            {
                var texture = sprites.Frame0(ssOption.ScreenSprite);
                var textureRect = new TextureRect
                {
                    Texture = texture,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    SetSize = new Vector2(128f, 128f), // Fill button
                    MouseFilter = MouseFilterMode.Ignore,
                    Margin = new Thickness(0, 50, 0, 0) // Shift down heavily (2x previous)
                };
                button.AddChild(textureRect);
            }
        }
        else if (model.Sprite != null)
        {
            var scale = Vector2.One;
            var texture = sprites.Frame0(model.Sprite);
            
            if (texture.Width <= 32)
            {
                scale *= 2;
            }

            button.TextureNormal = texture;
            button.Scale = scale;
        }

        if (model is RadialMenuActionOption actionOption)
        {
            button.OnPressed += _ =>
            {
                actionOption.OnPressed?.Invoke();
                Close();
            };
        }

        return button;
    }

    private RadialMenuTextureButton CreateNavigationButton(
        string tooltip,
        ResPath texturePath,
        SimpleRadialMenuSettings settings,
        SpriteSystem sprites)
    {
        var button = settings.UseSectors
            ? new RadialMenuTextureButtonWithSector
            {
                DrawBorder = settings.DisplayBorders,
                DrawBackground = !settings.NoBackground
            }
            : new RadialMenuTextureButton();

        // 2x smaller -> 32x32 (standard is 64x64)
        button.SetSize = new Vector2(32f, 32f); 
        button.ToolTip = tooltip;

        var texture = sprites.Frame0(new SpriteSpecifier.Texture(texturePath));
        button.TextureNormal = texture;
        // Adjust scale if needed, but 32x32 should fit standard icons fine
        // If texture is small (<= 32), we usually scale up, but here we want small button. 
        // Let's keep scale 1.0 or scale down if too big.
        button.Scale = Vector2.One;

        return button;
    }

    private void ClearExistingChildrenRadialButtons()
    {
        var toRemove = new List<Control>(ChildCount);
        foreach (var child in Children)
        {
            if (child != ContextualButton && child != MenuOuterAreaButton)
            {
                toRemove.Add(child);
            }
        }

        foreach (var control in toRemove)
        {
            Children.Remove(control);
        }
    }
}

public sealed class RadialMenuScreenSaverOption : RadialMenuActionOption
{
    public SpriteSpecifier? HeadSprite { get; }
    public SpriteSpecifier? ScreenSprite { get; }
    public Color? HeadColor { get; }

    public RadialMenuScreenSaverOption(
        Action onPressed, 
        SpriteSpecifier? headSprite, 
        SpriteSpecifier? screenSprite,
        Color? headColor = null) 
        : base(onPressed)
    {
        HeadSprite = headSprite;
        ScreenSprite = screenSprite;
        HeadColor = headColor;
    }
}
