using System.Linq;
using Content.Shared.Traits;
using Content.Shared._Pirate.Traits;
using Content.Shared.Preferences;
using Content.Shared._Pirate.Traits.Conditions;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Pirate.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IComponentFactory _compFactory = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => TraitCheckbox.Pressed;
    public readonly int TraitCost;
    public bool MeetsConditions { get; private set; } = true;

    private readonly TraitPrototype _trait;
    private bool _isUpdating;
    private readonly List<string> _failedConditionTooltips = new();

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        if (trait.Description != null)
            TraitDescriptionLabel.SetMessage(Loc.GetString(trait.Description));

        var displayCost = -trait.Cost;
        var costPrefix = displayCost > 0 ? "+" : "";
        var costColor = displayCost < 0 ? "#f87171" : displayCost > 0 ? "#4ade80" : "#888888";
        TraitCostLabel.Text = $"{costPrefix}{displayCost}";
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        TraitCheckbox.OnToggled += OnCheckboxToggled;

        UpdateConditionTooltips();
    }

    private void UpdateConditionTooltips()
    {
        var tooltips = new List<string>();

        foreach (var condition in _trait.Conditions)
        {
            var tooltip = condition.GetTooltip(_prototype, _loc);
            if (!string.IsNullOrEmpty(tooltip))
                tooltips.Add(tooltip);
        }

        if (tooltips.Count > 0)
        {
            var tooltipText = Loc.GetString("trait-conditions-tooltip",
                ("requirements", string.Join("\n", tooltips)));

            TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
        }
        else
            TooltipSupplier = null;
    }

    /// <summary>
    /// Creates a tooltip control that properly parses markup.
    /// </summary>
    private static Tooltip CreateMarkupTooltip(string markupText)
    {
        var tooltip = new Tooltip();

        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));

        return tooltip;
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species and conflicts.
    /// </summary>
    public void UpdateConditionsMet(HumanoidCharacterProfile? profile, HashSet<ProtoId<TraitPrototype>> selectedTraits, int remainingPoints)

    {
        var jobId = profile?.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High).Key;

        _failedConditionTooltips.Clear();
        MeetsConditions = true;

        var context = new TraitConditionContext
        {
            Player = EntityUid.Invalid,
            Session = null,
            EntMan = _entManager,
            Proto = _prototype,
            CompFactory = _compFactory,
            LogMan = _logManager,
            JobId = jobId?.Id,
            SpeciesId = profile?.Species.Id,
            Profile = profile
        };

        foreach (var condition in _trait.Conditions)
        {
            if (!condition.Evaluate(context))
            {
                MeetsConditions = false;
                var tooltip = condition.GetTooltip(_prototype, _loc);
                if (!string.IsNullOrEmpty(tooltip))
                    _failedConditionTooltips.Add(tooltip);
            }
        }

        var conflictingNames = new List<string>();
        foreach (var conflictId in _trait.Conflicts)
        {
            if (selectedTraits.Contains(conflictId) && conflictId != _trait.ID)
            {
                MeetsConditions = false;
                if (_prototype.TryIndex(conflictId, out var conflictingTrait))
                {
                    conflictingNames.Add(Loc.GetString(conflictingTrait.Name));
                }
            }
        }

        if (conflictingNames.Count > 0)
        {
            var conflictTooltip = Loc.GetString("trait-conditions-conflict-tooltip",
                ("traits", string.Join(", ", conflictingNames)));
            TooltipSupplier = _ => CreateMarkupTooltip(conflictTooltip);
        }

        var canAfford = remainingPoints >= TraitCost || selectedTraits.Contains(_trait.ID);
        UpdateDisabledState(canAfford);
    }

    private void UpdateDisabledState(bool canAfford)
    {
        if (!MeetsConditions)
        {
            TraitCheckbox.Visible = false;
            LockIcon.Visible = true;
            LockIcon.ModulateSelfOverride = Color.FromHex("#f87171");

            if (TraitCheckbox.Pressed)
            {
                _isUpdating = true;
                TraitCheckbox.Pressed = false;
                UpdateSelectedStyle();
                _isUpdating = false;
                OnToggled?.Invoke(false);
            }

            AddStyleClass("TraitsEntryUnavailable");
            RemoveStyleClass("TraitsEntryDisabled");
            RemoveStyleClass("TraitsEntryUnaffordable");
        }
        else if (!canAfford)
        {
            TraitCheckbox.Visible = false;
            LockIcon.Visible = true;
            LockIcon.ModulateSelfOverride = Color.FromHex("#fbbf24");

            AddStyleClass("TraitsEntryUnaffordable");
            RemoveStyleClass("TraitsEntryUnavailable");
            RemoveStyleClass("TraitsEntryDisabled");

            var tooltipText = Loc.GetString("trait-conditions-points-tooltip");
            TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
        }
        else
        {
            TraitCheckbox.Visible = true;
            LockIcon.Visible = false;

            RemoveStyleClass("TraitsEntryUnavailable");
            RemoveStyleClass("TraitsEntryDisabled");
            RemoveStyleClass("TraitsEntryUnaffordable");
            UpdateSelectedStyle();
            UpdateConditionTooltips();
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isUpdating)
            return;

        if (!MeetsConditions)
        {
            _isUpdating = true;
            TraitCheckbox.Pressed = false;
            _isUpdating = false;
            return;
        }

        UpdateSelectedStyle();
        OnToggled?.Invoke(args.Pressed);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        TraitCheckbox.Pressed = selected && MeetsConditions;
        UpdateSelectedStyle();
        _isUpdating = false;
    }

    private void UpdateSelectedStyle()
    {
        if (TraitCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
    }
}

