using System;
using System.Linq;
using Content.Shared.Traits;
using Content.Shared._Pirate.CCVars;
using Content.Shared._Pirate.Traits;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitsTab : BoxContainer
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    /// <summary>
    /// Event fired when trait selection changes.
    /// </summary>
    public event Action<HashSet<ProtoId<TraitPrototype>>>? OnTraitsChanged;

    private readonly Dictionary<ProtoId<TraitCategoryPrototype>, TraitCategory> _categoryUis = new();
    private readonly HashSet<ProtoId<TraitPrototype>> _selectedTraits = new();

    private int _maxGlobalTraits;
    private int _maxGlobalPoints;
    private int _currentTraitCount;
    private int _currentPointsSpent;

    private string _currentSearchText = string.Empty;
    private bool _awaitingLayoutUpdate;

    private HumanoidCharacterProfile? _profile;

    public TraitsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;
        ShowUnavailableCheckbox.OnToggled += OnShowUnavailableToggled;
        _prototype.PrototypesReloaded += OnProtoReload;

        _cfg.OnValueChanged(PirateVars.MaxTraitCount, OnMaxTraitCountChanged, true);
        _cfg.OnValueChanged(PirateVars.MaxTraitPoints, OnMaxTraitPointsChanged, true);

        PopulateCategories();
        UpdateGlobalStats();
    }

    private void OnMaxTraitCountChanged(int value)
    {
        _maxGlobalTraits = value;
        UpdateGlobalStats();
    }

    private void OnMaxTraitPointsChanged(int value)
    {
        _maxGlobalPoints = value;
        UpdateGlobalStats();
    }

    private void OnProtoReload(PrototypesReloadedEventArgs args)
    {
        if (Disposed)
            return;

        if (args.WasModified<TraitPrototype>() || args.WasModified<TraitCategoryPrototype>())
            RefreshTraits();
    }

    public void RefreshTraits()
    {
        PopulateCategories();
        UpdateGlobalStats();
    }

    private void PopulateCategories()
    {
        CategoriesContainer.RemoveAllChildren();
        _categoryUis.Clear();

        var categories = _prototype.EnumeratePrototypes<TraitCategoryPrototype>()
            .OrderBy(c => c.Priority)
            .ThenBy(c => Loc.GetString(c.Name))
            .ToList();

        var traitsByCategory = _prototype.EnumeratePrototypes<TraitPrototype>()
            .Where(t => t.Category != null)
            .GroupBy(t => t.Category!.Value)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(t => t.Cost).ThenBy(t => Loc.GetString(t.Name)).ToList());

        foreach (var category in categories)
        {
            if (!traitsByCategory.TryGetValue(category.ID, out var traits) || traits.Count == 0)
                continue;

            var categoryUi = new TraitCategory(category, traits);
            categoryUi.OnTraitToggled += OnTraitToggled;
            _categoryUis[category.ID] = categoryUi;
            CategoriesContainer.AddChild(categoryUi);
        }

        ApplySearchFilter();
        UpdateAllConditions();
    }

    private void OnTraitToggled(ProtoId<TraitPrototype> traitId, bool selected)
    {
        var trait = _prototype.Index(traitId);

        if (selected)
        {
            if (_currentTraitCount >= _maxGlobalTraits)
            {
                RevertTraitToggle(traitId);
                return;
            }

            if (_currentPointsSpent + trait.Cost > _maxGlobalPoints)
            {
                RevertTraitToggle(traitId);
                return;
            }

            if (trait.Category != null && _categoryUis.TryGetValue(trait.Category.Value, out var categoryUi))
            {
                var categoryProto = _prototype.Index(trait.Category.Value);
                if (categoryProto.MaxTraits.HasValue &&
                    categoryUi.SelectedCount >= categoryProto.MaxTraits.Value)
                {
                    RevertTraitToggle(traitId);
                    return;
                }

                if (categoryProto.MaxPoints.HasValue &&
                    categoryUi.PointsSpent + trait.Cost > categoryProto.MaxPoints.Value)
                {
                    RevertTraitToggle(traitId);
                    return;
                }

                if (!categoryUi.TraitMeetsConditions(traitId))
                {
                    RevertTraitToggle(traitId);
                    return;
                }
            }

            foreach (var conflict in trait.Conflicts)
            {
                if (!_selectedTraits.Contains(conflict))
                    continue;

                RevertTraitToggle(traitId);
                return;
            }

            _selectedTraits.Add(traitId);
            _currentTraitCount++;
            _currentPointsSpent += trait.Cost;
        }
        else
        {
            _selectedTraits.Remove(traitId);
            _currentTraitCount--;
            _currentPointsSpent -= trait.Cost;
        }

        UpdateGlobalStats();
        if (trait.Category != null)
            UpdateCategoryStats(trait.Category.Value);

        UpdateAllConditions();
        OnTraitsChanged?.Invoke(_selectedTraits);
    }

    private void RevertTraitToggle(ProtoId<TraitPrototype> traitId)
    {
        var trait = _prototype.Index(traitId);
        if (trait.Category != null && _categoryUis.TryGetValue(trait.Category.Value, out var categoryUi))
        {
            categoryUi.SetTraitSelected(traitId, _selectedTraits.Contains(traitId));
        }
    }

    private void UpdateGlobalStats()
    {
        GlobalTraitCountLabel.Text = $"{_currentTraitCount} / {_maxGlobalTraits}";

        var positiveCosts = 0;
        var negativeCosts = 0;

        foreach (var traitId in _selectedTraits)
        {
            if (!_prototype.TryIndex(traitId, out var trait))
                continue;

            if (trait.Cost > 0)
                positiveCosts += trait.Cost;
            else
                negativeCosts += trait.Cost;
        }

        var totalBudget = _maxGlobalPoints + Math.Abs(negativeCosts);
        var remainingPoints = totalBudget - positiveCosts;

        GlobalPointsLabel.Text = $"{remainingPoints} / {totalBudget}";

        var percentage = totalBudget > 0
            ? Math.Clamp((float)remainingPoints / totalBudget, 0f, 1f)
            : 0f;

        var parent = GlobalPointsBar.Parent;
        if (parent != null)
        {
            var parentWidth = parent.Width;
            if (parentWidth > 0)
            {
                GlobalPointsBar.SetWidth = (int)((parentWidth - 2) * percentage);
                _awaitingLayoutUpdate = false;
            }
            else if (!_awaitingLayoutUpdate)
            {
                _awaitingLayoutUpdate = true;
                parent.OnResized += OnProgressBarParentResized;
            }
        }

        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarFull");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarPartial");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarLow");
        GlobalPointsBar.RemoveStyleClass("TraitsProgressBarEmpty");

        GlobalPointsBar.AddStyleClass(percentage switch
        {
            >= 0.99f => "TraitsProgressBarFull",
            >= 0.5f => "TraitsProgressBarPartial",
            > 0f => "TraitsProgressBarLow",
            _ => "TraitsProgressBarEmpty"
        });
    }

    private void OnProgressBarParentResized()
    {
        _awaitingLayoutUpdate = false;
        UpdateGlobalStats();
    }

    private void UpdateCategoryStats(ProtoId<TraitCategoryPrototype> categoryId)
    {
        if (_categoryUis.TryGetValue(categoryId, out var categoryUi))
        {
            categoryUi.UpdateStats();
        }
    }

    private void OnShowUnavailableToggled(BaseButton.ButtonToggledEventArgs args)
    {
        ApplySearchFilter();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _currentSearchText = args.Text;
        ApplySearchFilter();
    }

    private void ApplySearchFilter()
    {
        var showUnavailable = ShowUnavailableCheckbox.Pressed;
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.FilterTraits(_currentSearchText, showUnavailable);
        }
    }

    /// <summary>
    /// Updates all trait conditions based on current job and species.
    /// Call this when job or species changes in the character creator.
    /// </summary>
    /// <param name="profile">Current profile</param>
    public void UpdateConditions(HumanoidCharacterProfile profile)
    {
        _profile = profile;
        UpdateAllConditions();
    }

    private void UpdateAllConditions()
    {
        var remainingPoints = _maxGlobalPoints - _currentPointsSpent;
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.UpdateConditions(_profile, _selectedTraits, remainingPoints);
        }

        RecalculateStats();
        ApplySearchFilter();
    }

    private void RecalculateStats()
    {
        _currentTraitCount = 0;
        _currentPointsSpent = 0;

        var previouslySelected = new HashSet<ProtoId<TraitPrototype>>(_selectedTraits);
        _selectedTraits.Clear();

        foreach (var (_, categoryUi) in _categoryUis)
        {
            var selectedInCategory = categoryUi.GetSelectedTraitIds();

            foreach (var traitId in selectedInCategory)
            {
                if (!_prototype.TryIndex(traitId, out var trait))
                    continue;

                _selectedTraits.Add(traitId);
                _currentTraitCount++;
                _currentPointsSpent += trait.Cost;
            }
        }

        UpdateGlobalStats();
        foreach (var (categoryId, _) in _categoryUis)
        {
            UpdateCategoryStats(categoryId);
        }

        if (!_selectedTraits.SetEquals(previouslySelected))
        {
            OnTraitsChanged?.Invoke(_selectedTraits);
        }
    }

    /// <summary>
    /// Sets the currently selected traits (e.g., when loading a profile).
    /// </summary>
    public void SetSelectedTraits(IEnumerable<ProtoId<TraitPrototype>> traits)
    {
        foreach (var (_, categoryUi) in _categoryUis)
        {
            categoryUi.ClearSelection();
        }

        _selectedTraits.Clear();
        _currentTraitCount = 0;
        _currentPointsSpent = 0;

        foreach (var traitId in traits)
        {
            if (!_prototype.TryIndex(traitId, out var trait))
                continue;

            _selectedTraits.Add(traitId);
            _currentTraitCount++;
            _currentPointsSpent += trait.Cost;

            if (trait.Category != null && _categoryUis.TryGetValue(trait.Category.Value, out var categoryUi))
            {
                categoryUi.SetTraitSelected(traitId, true);
            }
        }

        UpdateGlobalStats();
        foreach (var (categoryId, _) in _categoryUis)
        {
            UpdateCategoryStats(categoryId);
        }
    }
}
