// SPDX-FileCopyrightText: 2019 Remie Richards <remierichards@gmail.com>
// SPDX-FileCopyrightText: 2019 moneyl <8206401+Moneyl@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 Exp <theexp111@gmail.com>
// SPDX-FileCopyrightText: 2020 PrPleGoo <felix.leeuwen@gmail.com>
// SPDX-FileCopyrightText: 2020 Víctor Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 20kdc <asdd2808@gmail.com>
// SPDX-FileCopyrightText: 2021 Acruid <shatter66@gmail.com>
// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Galactic Chimp <63882831+GalacticChimp@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <gradientvera@outlook.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Ygg01 <y.laughing.man.y@gmail.com>
// SPDX-FileCopyrightText: 2021 mirrorcult <notzombiedude@gmail.com>
// SPDX-FileCopyrightText: 2022 0x6273 <0x40@keemail.me>
// SPDX-FileCopyrightText: 2022 Alex Evgrashin <aevgrashin@yandex.ru>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 AWF <you@example.com>
// SPDX-FileCopyrightText: 2024 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 GitHubUser53123 <110841413+GitHubUser53123@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Guillaume E <262623+quatre@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Kevin Zheng <kevinz5000@gmail.com>
// SPDX-FileCopyrightText: 2024 Kira Bridgeton <161087999+Verbalase@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Tayrtahn <tayrtahn@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Goobstation.Maths.FixedPoint;
using Content.Shared.Storage;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="ReagentDispenserComponent"/>.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ReagentDispenserWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        private AudioSystem _audioSystem = default!;
        private const float RecipeActionButtonSize = 28f;
        private const float RecipeChipHeight = 28f;
        private const float RecipeChipActionButtonSize = RecipeChipHeight;
        private const float RecipeChipColorSwatchSize = 14f;
        private const float RecipeChipColorSwatchSlotWidth = 16f;
        private const int RecipeChipColumns = 3;
        private static readonly SoundSpecifier InterfaceClickSound = new SoundPathSpecifier("/Audio/UserInterface/click.ogg");
        private DialogWindow? _saveRecipeDialog;
        private bool _isRecordingRecipe;
        private bool? _recordButtonIsCancel;
        public event Action<ItemStorageLocation>? OnDispenseReagentButtonPressed;
        public event Action<ItemStorageLocation>? OnEjectJugButtonPressed;
        public event Action? OnStartRecipeRecordingPressed;
        public event Action? OnCancelRecipeRecordingPressed;
        public event Action<string>? OnSaveRecipePressed;
        public event Action? OnClearRecipesPressed;
        public event Action<string>? OnDispenseRecipePressed;
        public event Action<string>? OnDeleteRecipePressed;
        public event Action<string>? OnSaveRecipeToDiskPressed;
        public event Action<string>? OnCopyDiskRecipePressed;
        public event Action<string>? OnDispenseDiskRecipePressed;
        public event Action<string>? OnDeleteDiskRecipePressed;
        public event Action? OnEjectRecipeDiskPressed;

        /// <summary>
        /// Create and initialize the dispenser UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the dispenser.
        /// </summary>
        public ReagentDispenserWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _audioSystem = _entityManager.System<AudioSystem>();

            RecordRecipeButton.OnPressed += _ =>
            {
                if (_isRecordingRecipe)
                    OnCancelRecipeRecordingPressed?.Invoke();
                else
                    OnStartRecipeRecordingPressed?.Invoke();
            };
            SaveRecipeButton.OnPressed += _ =>
            {
                PlayRecipeUiClickSound();
                OpenSaveRecipeDialog();
            };
            ClearRecipesButton.OnPressed += _ =>
            {
                OnClearRecipesPressed?.Invoke();
            };
            EjectRecipeDiskButton.OnPressed += _ =>
            {
                OnEjectRecipeDiskPressed?.Invoke();
            };

            ConfigureRecipeActionButton(RecordRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-record.svg.192dpi.png");
            ConfigureRecipeActionButton(SaveRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-save.svg.192dpi.png");
            ConfigureRecipeActionButton(ClearRecipesButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-delete-all.svg.192dpi.png");
            ConfigureRecipeActionButton(EjectRecipeDiskButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-eject.svg.192dpi.png");
            RecipeList.OnResized += () => ApplyRecipeChipWidths(RecipeList);
            RecipeDiskList.OnResized += () => ApplyRecipeChipWidths(RecipeDiskList);

            OnClose += () => _saveRecipeDialog?.Close();
        }

        /// <summary>
        /// Update the button grid of reagents which can be dispensed.
        /// </summary>
        /// <param name="inventory">Reagents which can be dispensed by this dispenser</param>
        public void UpdateReagentsList(List<ReagentInventoryItem> inventory)
        {
            if (ReagentList == null)
                return;

            ReagentList.Children.Clear();
            //Sort inventory by reagentLabel
            inventory.Sort((x, y) => x.ReagentLabel.CompareTo(y.ReagentLabel));

            foreach (var item in inventory)
            {
                var card = new ReagentCardControl(item);
                card.OnPressed += OnDispenseReagentButtonPressed;
                card.OnEjectButtonPressed += OnEjectJugButtonPressed;
                ReagentList.Children.Add(card);
            }
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ReagentDispenserBoundUserInterfaceState) state;
            UpdateContainerInfo(castState);
            UpdateReagentsList(castState.Inventory);
            UpdateRecipes(castState);

            _entityManager.TryGetEntity(castState.OutputContainerEntity, out var outputContainerEnt);
            View.SetEntity(outputContainerEnt);

            // Disable the Clear & Eject button if no beaker
            ClearButton.Disabled = castState.OutputContainer is null;
            EjectButton.Disabled = castState.OutputContainer is null;

            AmountGrid.Selected = ((int)castState.SelectedDispenseAmount).ToString();
        }

        private void UpdateRecipes(ReagentDispenserBoundUserInterfaceState state)
        {
            _isRecordingRecipe = state.IsRecordingRecipe;
            ConfigureRecordingButton(state.IsRecordingRecipe);
            SaveRecipeButton.Disabled = !state.IsRecordingRecipe || state.RecordingRecipeReagents.Count == 0;
            ClearRecipesButton.Disabled = state.SavedRecipes.Count == 0;
            RecipeDiskSection.Visible = state.HasRecipeDisk;
            EjectRecipeDiskButton.Disabled = !state.HasRecipeDisk;

            RecipeList.Children.Clear();
            foreach (var recipe in state.SavedRecipes)
            {
                var chip = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = false,
                };

                chip.AddChild(CreateRecipeColorSwatch(recipe.Color));

                var loadButton = new Button
                {
                    Text = recipe.Name,
                    StyleClasses = { StyleBase.ButtonOpenRight },
                    HorizontalExpand = true,
                    MinHeight = RecipeChipHeight,
                    SetHeight = RecipeChipHeight,
                    ClipText = true,
                };
                loadButton.OnPressed += _ =>
                {
                    OnDispenseRecipePressed?.Invoke(recipe.Name);
                };

                var saveToDiskButton = new Button
                {
                    HorizontalExpand = false,
                    StyleClasses = { StyleBase.ButtonOpenBoth },
                    MinWidth = RecipeChipActionButtonSize,
                    SetWidth = RecipeChipActionButtonSize,
                    Disabled = !state.HasRecipeDisk,
                    ToolTip = Loc.GetString("reagent-dispenser-window-recipes-save-to-disk-tooltip"),
                };
                ConfigureCompactIconButton(saveToDiskButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-download-from-disk.svg.192dpi.png");
                saveToDiskButton.OnPressed += _ =>
                {
                    OnSaveRecipeToDiskPressed?.Invoke(recipe.Name);
                };

                var deleteButton = new Button
                {
                    HorizontalExpand = false,
                    StyleClasses = { StyleBase.ButtonOpenLeft },
                    MinWidth = RecipeChipActionButtonSize,
                    SetWidth = RecipeChipActionButtonSize,
                    ToolTip = Loc.GetString("reagent-dispenser-window-recipes-delete-tooltip"),
                };
                ConfigureCompactIconButton(deleteButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-delete.svg.192dpi.png");
                deleteButton.OnPressed += _ =>
                {
                    OnDeleteRecipePressed?.Invoke(recipe.Name);
                };

                chip.AddChild(loadButton);
                chip.AddChild(saveToDiskButton);
                chip.AddChild(deleteButton);
                RecipeList.AddChild(chip);
            }
            ApplyRecipeChipWidths(RecipeList);

            if (state.SavedRecipes.Count == 0)
            {
                RecipeList.AddChild(new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-recipes-none"),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                });
            }

            RecipeDiskList.Children.Clear();
            if (!state.HasRecipeDisk)
                return;

            foreach (var recipe in state.DiskRecipes)
            {
                var chip = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = false,
                };

                chip.AddChild(CreateRecipeColorSwatch(recipe.Color));

                var nameButton = new Button
                {
                    Text = recipe.Name,
                    StyleClasses = { StyleBase.ButtonOpenRight },
                    HorizontalExpand = true,
                    MinHeight = RecipeChipHeight,
                    SetHeight = RecipeChipHeight,
                    ClipText = true,
                    ToolTip = Loc.GetString("reagent-dispenser-window-recipes-copy-from-disk-tooltip"),
                };
                nameButton.OnPressed += _ =>
                {
                    OnDispenseDiskRecipePressed?.Invoke(recipe.Name);
                };

                var uploadButton = new Button
                {
                    HorizontalExpand = false,
                    StyleClasses = { StyleBase.ButtonOpenBoth },
                    MinWidth = RecipeChipActionButtonSize,
                    SetWidth = RecipeChipActionButtonSize,
                    ToolTip = Loc.GetString("reagent-dispenser-window-recipes-copy-from-disk-tooltip"),
                };
                ConfigureCompactIconButton(uploadButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-save-to-disk.svg.192dpi.png");
                uploadButton.OnPressed += _ =>
                {
                    OnCopyDiskRecipePressed?.Invoke(recipe.Name);
                };

                var deleteButton = new Button
                {
                    HorizontalExpand = false,
                    StyleClasses = { StyleBase.ButtonOpenLeft },
                    MinWidth = RecipeChipActionButtonSize,
                    SetWidth = RecipeChipActionButtonSize,
                    ToolTip = Loc.GetString("reagent-dispenser-window-recipes-delete-disk-tooltip"),
                };
                ConfigureCompactIconButton(deleteButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-delete.svg.192dpi.png");
                deleteButton.OnPressed += _ =>
                {
                    OnDeleteDiskRecipePressed?.Invoke(recipe.Name);
                };

                chip.AddChild(nameButton);
                chip.AddChild(uploadButton);
                chip.AddChild(deleteButton);
                RecipeDiskList.AddChild(chip);
            }
            ApplyRecipeChipWidths(RecipeDiskList);

            if (state.DiskRecipes.Count == 0)
            {
                RecipeDiskList.AddChild(new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-recipes-disk-none"),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                });
            }
        }

        private void ConfigureRecipeActionButton(Button button, string texturePath)
        {
            button.Text = string.Empty;
            button.HorizontalExpand = false;
            button.MinWidth = RecipeActionButtonSize;
            button.SetWidth = RecipeActionButtonSize;
            button.MinHeight = RecipeActionButtonSize;
            button.SetHeight = RecipeActionButtonSize;
            button.RemoveAllChildren();
            button.AddChild(new TextureRect
            {
                TexturePath = texturePath,
                MinSize = new Vector2(16f, 16f),
                MaxSize = new Vector2(16f, 16f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            });
        }

        private void PlayRecipeUiClickSound()
        {
            _audioSystem.PlayGlobal(InterfaceClickSound, Filter.Local(), false, AudioParams.Default.WithVolume(-2f));
        }

        private void ConfigureCompactIconButton(Button button, string texturePath)
        {
            button.Text = string.Empty;
            button.MinHeight = RecipeChipActionButtonSize;
            button.SetHeight = RecipeChipActionButtonSize;
            button.RemoveAllChildren();
            button.AddChild(new TextureRect
            {
                TexturePath = texturePath,
                MinSize = new Vector2(16f, 16f),
                MaxSize = new Vector2(16f, 16f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            });
        }

        private void ConfigureRecordingButton(bool isRecordingRecipe)
        {
            if (_recordButtonIsCancel == isRecordingRecipe)
                return;

            _recordButtonIsCancel = isRecordingRecipe;
            ConfigureRecipeActionButton(
                RecordRecipeButton,
                isRecordingRecipe
                    ? "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-cancel.svg.192dpi.png"
                    : "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-record.svg.192dpi.png");
            RecordRecipeButton.ToolTip = Loc.GetString(
                isRecordingRecipe
                    ? "reagent-dispenser-window-recipes-cancel-tooltip"
                    : "reagent-dispenser-window-recipes-record-tooltip");
        }

        private CenterContainer CreateRecipeColorSwatch(Color color)
        {
            return new CenterContainer
            {
                MinWidth = RecipeChipColorSwatchSlotWidth,
                SetWidth = RecipeChipColorSwatchSlotWidth,
                Margin = new Thickness(0f, 0f, 1f, 0f),
                Children =
                {
                    new PanelContainer
                    {
                        MinSize = new Vector2(RecipeChipColorSwatchSize, RecipeChipColorSwatchSize),
                        MaxSize = new Vector2(RecipeChipColorSwatchSize, RecipeChipColorSwatchSize),
                        PanelOverride = new StyleBoxFlat { BackgroundColor = color },
                    }
                }
            };
        }

        private void OpenSaveRecipeDialog()
        {
            if (_saveRecipeDialog != null)
            {
                _saveRecipeDialog.MoveToFront();
                return;
            }

            const string field = "name";
            var entry = new QuickDialogEntry(
                field,
                QuickDialogEntryType.ShortText,
                Loc.GetString("reagent-dispenser-window-recipes-save-dialog-prompt"),
                Loc.GetString("reagent-dispenser-window-recipes-save-dialog-placeholder"));

            _saveRecipeDialog = new DialogWindow(
                Loc.GetString("reagent-dispenser-window-recipes-save-dialog-title"),
                new List<QuickDialogEntry> { entry });
            _saveRecipeDialog.MinHeight = 0f;
            _saveRecipeDialog.SetHeight = float.NaN;

            _saveRecipeDialog.OnConfirmed += responses =>
            {
                var name = responses[field].Trim();
                if (name.Length > SharedReagentDispenser.RecipeNameMaxLength)
                    name = name[..SharedReagentDispenser.RecipeNameMaxLength];

                if (!string.IsNullOrEmpty(name))
                    OnSaveRecipePressed?.Invoke(name);
            };

            _saveRecipeDialog.OnClose += () => _saveRecipeDialog = null;
        }

        private void ApplyRecipeChipWidths(GridContainer container)
        {
            if (container.PixelWidth <= 0)
                return;

            var chipWidth = container.PixelWidth / (float) RecipeChipColumns;
            foreach (var child in container.Children)
            {
                if (child is not BoxContainer chip)
                    continue;

                chip.MinWidth = chipWidth;
                chip.MaxWidth = chipWidth;
                chip.SetWidth = chipWidth;
            }
        }

        /// <summary>
        /// Update the fill state and list of reagents held by the current reagent container, if applicable.
        /// <para>Also highlights a reagent if it's dispense button is being mouse hovered.</para>
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        /// or null if no button is being hovered.</param>
        public void UpdateContainerInfo(ReagentDispenserBoundUserInterfaceState state)
        {
            ContainerInfo.Children.Clear();

            if (state.IsRecordingRecipe)
            {
                ContainerInfoName.Text = Loc.GetString("reagent-dispenser-window-recipes-virtual-container-name");
                var total = state.RecordingRecipeReagents.Aggregate(FixedPoint2.Zero, (current, reagent) => current + reagent.Quantity).Int();
                ContainerInfoFill.Text = $"{total}u";
                UpdateVirtualRecordingContents(state.RecordingRecipeReagents);
                return;
            }

            if (state.OutputContainer is null)
            {
                ContainerInfoName.Text = "";
                ContainerInfoFill.Text = "";
                ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });

                return;
            }

            // Set Name of the container and its fill status (Ex: 44/100u)
            ContainerInfoName.Text = state.OutputContainer.DisplayName;
            ContainerInfoFill.Text = state.OutputContainer.CurrentVolume + "/" + state.OutputContainer.MaxVolume;

            foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
            {
                // Try get to the prototype for the given reagent. This gives us its name.
                var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? p)
                    ? p.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    }
                });
            }
        }

        private void UpdateVirtualRecordingContents(IReadOnlyCollection<ReagentQuantity> reagents)
        {
            if (reagents.Count == 0)
            {
                ContainerInfo.Children.Add(new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-recipes-virtual-container-empty"),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                });
                return;
            }

            foreach (var reagent in reagents.OrderBy(r => r.Reagent.Prototype))
            {
                var localizedName = _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? p)
                    ? p.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", reagent.Quantity)),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    }
                });
            }
        }
    }
}
