using System;
using System.Collections.Generic;
using Content.Pirate.Shared.IntegratedCircuits.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Pirate.Client.IntegratedCircuits.UI;

[GenerateTypedNameReferences]
public sealed partial class AssemblyInteractWindow : DefaultWindow
{
    public event Action<NetEntity>? OnOptionSelected;

    private List<InteractOption> _currentOptions = new();

    public AssemblyInteractWindow()
    {
        RobustXamlLoader.Load(this);

        // Динамічне оновлення списку під час введення тексту
        FilterEdit.OnTextChanged += _ => FilterList(FilterEdit.Text);
    }

    public void UpdateState(AssemblyInteractBoundUIState state)
    {
        _currentOptions = state.Options;
        FilterList(FilterEdit.Text);
    }

    private void FilterList(string filter)
    {
        OptionsContainer.RemoveAllChildren();

        foreach (var option in _currentOptions)
        {
            // Якщо поле фільтра не порожнє, ігноруємо регістр і перевіряємо, чи збігається текст
            if (!string.IsNullOrWhiteSpace(filter) && 
                !option.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var btn = new Button
            {
                Text = option.Name,
                HorizontalAlignment = HAlignment.Stretch,
                Margin = new Robust.Shared.Maths.Thickness(0, 0, 0, 2)
            };

            var netEntity = option.CircuitEntity;
            btn.OnPressed += _ => OnOptionSelected?.Invoke(netEntity);
            
            OptionsContainer.AddChild(btn);
        }
    }
}
