using System;
using System.Collections.Generic;
using System.Linq;
using Content.Pirate.Shared.IntegratedCircuits.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.IntegratedCircuits.UI;

[GenerateTypedNameReferences]
public sealed partial class CircuitPrinterWindow : DefaultWindow
{
    /// <summary>
    /// Fired when the player clicks on a recipe to build it.
    /// </summary>
    public event Action<string>? OnBuildPressed;

    /// <summary>
    /// Fired when the player selects a different category tab.
    /// </summary>
    public event Action<string>? OnCategorySelected;

    private string _currentCategory = string.Empty;
    private bool _upgraded;

    public CircuitPrinterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CircuitPrinterBoundUIState state)
    {
        _upgraded = state.Upgraded;
        _currentCategory = state.CurrentCategory;

        // Materials
        var materialParts = new List<string>();
        foreach (var (material, amount) in state.Materials)
        {
            materialParts.Add($"{amount}/{state.MaterialMax} {material}");
        }
        MaterialsLabel.Text = materialParts.Count > 0
            ? string.Join("; ", materialParts)
            : Loc.GetString("circuit-printer-window-materials-none");

        // Upgrade status
        UpgradeLabel.Text = state.Upgraded ? Loc.GetString("circuit-printer-window-upgraded-advanced") : Loc.GetString("circuit-printer-window-upgraded-regular");

        // Category tabs
        CategoriesContainer.RemoveAllChildren();
        foreach (var category in state.Categories.Keys)
        {
            var btn = new Button
            {
                Text = $"[{category}]",
                Margin = new Robust.Shared.Maths.Thickness(2, 0, 2, 0),
            };

            if (category == _currentCategory)
            {
                btn.Disabled = true;
            }

            var capturedCategory = category;
            btn.OnPressed += _ => OnCategorySelected?.Invoke(capturedCategory);
            CategoriesContainer.AddChild(btn);
        }

        // Category header
        CategoryHeader.Text = _currentCategory;

        // Recipe list
        RecipesList.RemoveAllChildren();
        if (state.Categories.TryGetValue(_currentCategory, out var recipes))
        {
            foreach (var recipe in recipes)
            {
                var row = CreateRecipeRow(recipe);
                RecipesList.AddChild(row);
            }
        }
    }

    private BoxContainer CreateRecipeRow(PrinterRecipeEntry recipe)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Robust.Shared.Maths.Thickness(0, 1, 0, 1),
        };

        var canBuild = !recipe.RequiresUpgrade || _upgraded;

        if (canBuild)
        {
            var buildBtn = new Button
            {
                Text = $"[{recipe.Name}]",
                MinSize = new System.Numerics.Vector2(180, 0),
            };
            var capturedId = recipe.RecipeId;
            buildBtn.OnPressed += _ => OnBuildPressed?.Invoke(capturedId);
            row.AddChild(buildBtn);
        }
        else
        {
            // Show as strikethrough / disabled
            var disabledLabel = new Label
            {
                Text = $"[{recipe.Name}]",
                MinSize = new System.Numerics.Vector2(180, 0),
                Modulate = new Robust.Shared.Maths.Color(0.4f, 0.4f, 0.4f),
            };
            row.AddChild(disabledLabel);
        }

        // Description
        var descLabel = new Label
        {
            Text = $": {recipe.Description}",
            HorizontalExpand = true,
        };
        row.AddChild(descLabel);

        // Cost
        if (recipe.Cost.Count > 0)
        {
            var costParts = recipe.Cost.Select(kv => $"{kv.Value} {kv.Key}");
            var costLabel = new Label
            {
                Text = $" ({string.Join(", ", costParts)})",
                Modulate = new Robust.Shared.Maths.Color(0.6f, 0.8f, 1.0f),
            };
            row.AddChild(costLabel);
        }

        return row;
    }
}
