using System;
using Content.Pirate.Shared.IntegratedCircuits.Components;
using Content.Pirate.Shared.IntegratedCircuits.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Pirate.Client.IntegratedCircuits.UI;

[GenerateTypedNameReferences]
public sealed partial class CircuitDebuggerWindow : DefaultWindow
{
    public event Action<DebuggerMode>? OnModeSelected;
    public event Action<string>? OnDataSaved;

    public CircuitDebuggerWindow()
    {
        RobustXamlLoader.Load(this);

        BtnString.OnPressed += _ => OnModeSelected?.Invoke(DebuggerMode.String);
        BtnNumber.OnPressed += _ => OnModeSelected?.Invoke(DebuggerMode.Number);
        BtnRef.OnPressed += _ => OnModeSelected?.Invoke(DebuggerMode.Ref);
        BtnNull.OnPressed += _ => OnModeSelected?.Invoke(DebuggerMode.Null);

        BtnSave.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(DataInput.Text))
                OnDataSaved?.Invoke(DataInput.Text);
        };
        
        // Також зберігаємо при натисканні Enter
        DataInput.OnTextEntered += args =>
        {
            if (!string.IsNullOrWhiteSpace(args.Text))
                OnDataSaved?.Invoke(args.Text);
        };
    }

    public void UpdateState(CircuitDebuggerBoundUIState state)
    {
        CurrentValueLabel.Text = state.CurrentDataDisplay;

        // Скидаємо стилі кнопок
        BtnString.StyleClasses.Remove("ButtonColorGreen");
        BtnNumber.StyleClasses.Remove("ButtonColorGreen");
        BtnRef.StyleClasses.Remove("ButtonColorGreen");
        BtnNull.StyleClasses.Remove("ButtonColorGreen");

        // Підсвічуємо активну кнопку і показуємо/ховаємо поля
        InputContainer.Visible = false;
        RefPromptLabel.Visible = false;

        switch (state.Mode)
        {
            case DebuggerMode.String:
                BtnString.StyleClasses.Add("ButtonColorGreen");
                InputContainer.Visible = true;
                break;
            case DebuggerMode.Number:
                BtnNumber.StyleClasses.Add("ButtonColorGreen");
                InputContainer.Visible = true;
                break;
            case DebuggerMode.Ref:
                BtnRef.StyleClasses.Add("ButtonColorGreen");
                RefPromptLabel.Visible = state.AcceptingRefs;
                break;
            case DebuggerMode.Null:
                BtnNull.StyleClasses.Add("ButtonColorGreen");
                break;
        }
    }
}
