using System;
using System.Collections.Generic;
using Content.Pirate.Shared.IntegratedCircuits;
using Content.Pirate.Shared.IntegratedCircuits.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Client.UserInterface; 
using Robust.Client.UserInterface.Controls;

namespace Content.Pirate.Client.IntegratedCircuits.UI;

[GenerateTypedNameReferences]
public sealed partial class ElectronicAssemblyWindow : DefaultWindow
{
    public event Action<NetEntity>? OnRemoveCircuit;
    public event Action<string>? OnRenamePressed;
    public event Action? OnRemoveBattery;
    public event Action<NetEntity, PinType, int>? OnPinClicked;

    private NetEntity? _selectedCircuitId;
    private ElectronicAssemblyBoundUIState? _lastState;

    public ElectronicAssemblyWindow()
    {
        RobustXamlLoader.Load(this);

        RenameButton.OnPressed += _ =>
        {
            if (AssemblyNameEdit.Visible)
            {
                OnRenamePressed?.Invoke(AssemblyNameEdit.Text);
                AssemblyNameEdit.Visible = false;
                AssemblyNameLabel.Visible = true;
                RenameButton.Text = "[Rename]";
            }
            else
            {
                AssemblyNameEdit.Text = AssemblyNameLabel.Text ?? "";
                AssemblyNameEdit.Visible = true;
                AssemblyNameLabel.Visible = false;
                RenameButton.Text = "[Save]";
                AssemblyNameEdit.GrabKeyboardFocus();
            }
        };

        RemoveBatteryButton.OnPressed += _ => OnRemoveBattery?.Invoke();

        RemoveCircuitButton.OnPressed += _ =>
        {
            if (_selectedCircuitId != null) 
                OnRemoveCircuit?.Invoke(_selectedCircuitId.Value);
        };
    }

    public void UpdateState(ElectronicAssemblyBoundUIState state)
    {
        _lastState = state;
        AssemblyNameLabel.Text = state.AssemblyName;
        Title = state.AssemblyName;

        StatsLabel.Text = $"Space: {state.TotalSize}/{state.MaxSize} | Complexity: {state.TotalComplexity}/{state.MaxComplexity}";
        
        if (state.HasBattery)
        {
            BatteryLabel.Text = $"Power: {state.BatteryCharge:F0}/{state.BatteryMaxCharge:F0}J";
            BatteryLabel.StyleClasses.Clear();
            RemoveBatteryButton.Visible = true;
        }
        else
        {
            BatteryLabel.Text = "Power: No Cell";
            if (!BatteryLabel.StyleClasses.Contains("LabelDanger"))
                BatteryLabel.StyleClasses.Add("LabelDanger");
            RemoveBatteryButton.Visible = false;
        }

        ComponentsList.RemoveAllChildren();
        AssemblyCircuitEntry? selectedData = null;

        foreach (var circuit in state.Circuits)
        {
            var btn = new Button
            {
                Text = circuit.Name,
                HorizontalAlignment = HAlignment.Stretch,
                StyleClasses = { "OpenBoth" },
                Pressed = _selectedCircuitId == circuit.NetEntity,
                ToggleMode = true
            };

            if (btn.Pressed) selectedData = circuit;

            var capturedEntity = circuit.NetEntity;
            btn.OnPressed += _ => SelectCircuit(capturedEntity);
            ComponentsList.AddChild(btn);
        }

        if (selectedData != null)
        {
            CircuitDetailsPanel.Visible = true;
            SelectPromptLabel.Visible = false;
            BuildCircuitDetails(selectedData);
        }
        else
        {
            CircuitDetailsPanel.Visible = false;
            SelectPromptLabel.Visible = true;
        }
    }

    private void SelectCircuit(NetEntity id)
    {
        _selectedCircuitId = id;
        if (_lastState != null) UpdateState(_lastState);
    }

    private void BuildCircuitDetails(AssemblyCircuitEntry circuit)
    {
        DetailNameLabel.Text = circuit.Name;
        DetailDescLabel.Text = circuit.Description;
        RemoveCircuitButton.Disabled = !circuit.Removable;

        StatSize.Text = $"Size: {circuit.Size}";
        StatComp.Text = $"Complexity: {circuit.Complexity}";
        StatPower.Text = $"Power (Idle): {circuit.PowerDrawIdle}W";
        StatActive.Text = $"Power (Act): {circuit.PowerDrawPerUse}W";

        InputsContainer.RemoveAllChildren();
        OutputsContainer.RemoveAllChildren();
        ActivatorsContainer.RemoveAllChildren();

        for (int i = 0; i < circuit.InputPins.Count; i++)
        {
            InputsContainer.AddChild(CreatePinControl(circuit.NetEntity, circuit.InputPins[i], i));
        }

        for (int i = 0; i < circuit.OutputPins.Count; i++)
        {
            OutputsContainer.AddChild(CreatePinControl(circuit.NetEntity, circuit.OutputPins[i], i));
        }

        for (int i = 0; i < circuit.ActivatorPins.Count; i++)
        {
            ActivatorsContainer.AddChild(CreatePinControl(circuit.NetEntity, circuit.ActivatorPins[i], i));
        }
    }

    private Control CreatePinControl(NetEntity circuitId, CircuitPinInfo pin, int index)
    {
        var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Robust.Shared.Maths.Thickness(0,0,0,5) };
        
        var btn = new Button
        {
            Text = $"[{pin.DataType}] {pin.Name} : {pin.DisplayData}",
            ToolTip = "Click with Wirer to connect. Click with Debugger to write data.",
            Modulate = pin.PinType == PinType.Activator ? Robust.Shared.Maths.Color.IndianRed : Robust.Shared.Maths.Color.LightGray
        };

        if (pin.IsConnected)
            btn.StyleClasses.Add("ButtonColorGreen");

        btn.OnPressed += _ => OnPinClicked?.Invoke(circuitId, pin.PinType, index);
        box.AddChild(btn);

        if (pin.IsConnected && !string.IsNullOrEmpty(pin.ConnectedTo))
        {
            box.AddChild(new Label { Text = " └─> " + pin.ConnectedTo, Modulate = Robust.Shared.Maths.Color.DarkGray, Margin = new Robust.Shared.Maths.Thickness(10,0,0,0) });
        }

        return box;
    }
}
