using System;
using System.Collections.Generic;
using Content.Pirate.Shared.IntegratedCircuits.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Pirate.Client.IntegratedCircuits.UI;

[GenerateTypedNameReferences]
public sealed partial class ElectronicAssemblyWindow : DefaultWindow
{
    /// <summary>
    /// Fired when the player clicks [Remove] on a circuit.
    /// </summary>
    public event Action<NetEntity>? OnRemoveCircuit;

    /// <summary>
    /// Fired when the player changes the assembly name.
    /// </summary>
    public event Action<string>? OnRenamePressed;

    /// <summary>
    /// Fired when the player clicks [Remove] on the battery.
    /// </summary>
    public event Action? OnRemoveBattery;

    public ElectronicAssemblyWindow()
    {
        RobustXamlLoader.Load(this);

        RenameButton.OnPressed += _ =>
        {
            if (AssemblyNameEdit.Visible)
            {
                // Save pressed
                OnRenamePressed?.Invoke(AssemblyNameEdit.Text);
                AssemblyNameEdit.Visible = false;
                AssemblyNameLabel.Visible = true;
                RenameButton.Text = "[Rename]";
            }
            else
            {
                // Rename pressed
                AssemblyNameEdit.Text = AssemblyNameLabel.Text ?? "";
                AssemblyNameEdit.Visible = true;
                AssemblyNameLabel.Visible = false;
                RenameButton.Text = "[Save]";
                AssemblyNameEdit.GrabKeyboardFocus();
            }
        };

        RemoveBatteryButton.OnPressed += _ => OnRemoveBattery?.Invoke();
    }

    public void UpdateState(ElectronicAssemblyBoundUIState state)
    {
        // Assembly name
        AssemblyNameLabel.Text = state.AssemblyName;
        Title = state.AssemblyName;

        // Size / complexity
        SizeLabel.Text = $"{state.TotalSize}/{state.MaxSize} space taken up in the assembly.";
        ComplexityLabel.Text = $"{state.TotalComplexity}/{state.MaxComplexity} complexity in the assembly.";

        // Battery
        if (state.HasBattery)
        {
            var percent = state.BatteryMaxCharge > 0
                ? Math.Round(state.BatteryCharge / state.BatteryMaxCharge * 100f, 1)
                : 0;
            BatteryLabel.Text = $"{state.BatteryCharge:F1}/{state.BatteryMaxCharge:F0} ({percent}%) cell charge.";
            BatteryLabel.StyleClasses.Clear();
            RemoveBatteryButton.Visible = true;
        }
        else
        {
            BatteryLabel.Text = "No power cell detected!";
            if (!BatteryLabel.StyleClasses.Contains("LabelDanger"))
                BatteryLabel.StyleClasses.Add("LabelDanger");
            RemoveBatteryButton.Visible = false;
        }

        // Components list
        ComponentsList.RemoveAllChildren();

        if (state.Circuits.Count > 0)
        {
            ComponentsHeader.Visible = true;

            for (var i = 0; i < state.Circuits.Count; i++)
            {
                var circuit = state.Circuits[i];
                var row = CreateCircuitRow(i + 1, circuit);
                ComponentsList.AddChild(row);
            }
        }
        else
        {
            ComponentsHeader.Visible = false;
        }
    }

    private BoxContainer CreateCircuitRow(int slot, AssemblyCircuitEntry circuit)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Robust.Shared.Maths.Thickness(0, 1, 0, 1),
        };

        // Slot number
        var slotLabel = new Label
        {
            Text = $"[ {slot} ] | ",
            MinSize = new System.Numerics.Vector2(60, 0),
        };
        row.AddChild(slotLabel);

        // Remove button
        if (circuit.Removable)
        {
            var removeBtn = new Button
            {
                Text = "[-]",
                MinSize = new System.Numerics.Vector2(35, 0),
            };
            var capturedEntity = circuit.NetEntity;
            removeBtn.OnPressed += _ => OnRemoveCircuit?.Invoke(capturedEntity);
            row.AddChild(removeBtn);
        }
        else
        {
            var disabledLabel = new Label
            {
                Text = "[-]",
                MinSize = new System.Numerics.Vector2(35, 0),
                Modulate = new Robust.Shared.Maths.Color(0.5f, 0.5f, 0.5f),
            };
            row.AddChild(disabledLabel);
        }

        // Separator
        row.AddChild(new Label { Text = " | " });

        // Circuit name
        var nameLabel = new Label
        {
            Text = circuit.Name,
            HorizontalExpand = true,
        };
        row.AddChild(nameLabel);

        return row;
    }
}
