// SPDX-FileCopyrightText: 2024 Milon <milonpl.git@proton.me>
// SPDX-FileCopyrightText: 2024 Skubman <ba.fallaria@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2025 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 deltanedas <@deltanedas:kde.org>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility; // Goob

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBubblePirate : BoxContainer
{
    public static readonly Color OwnMessageColor = Color.FromHex("#1f402fd9");
    public static readonly Color OtherMessageColor = Color.FromHex("#3b4258f0");
    public static readonly Color BorderColor = Color.FromHex("#00000000");
    public static readonly Color TextColor = Color.FromHex("#e1e6f0");
    public static readonly Color ErrorColor = Color.FromHex("#cc3333");
    private bool? _previousIsOwnMessage;

    public NanoChatMessageBubblePirate()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMessage(NanoChatMessage message, bool isOwnMessage)
    {
        if (MessagePanel.PanelOverride is not StyleBoxFlat style)
            return;

        // Configure message appearance
        style.BackgroundColor = isOwnMessage ? OwnMessageColor : OtherMessageColor;
        style.BorderColor = BorderColor;
        style.BorderThickness = new Thickness(0);

        // Set message content
        MessageText.Text = FormattedMessage.EscapeText(message.Content); // Goob Sanitize Text
        MessageText.Modulate = TextColor;

        // Show delivery failed text if needed (only for own messages)
        DeliveryFailedLabel.Visible = isOwnMessage && message.DeliveryFailed;
        DeliveryFailedLabel.HorizontalAlignment = HAlignment.Right;
        if (DeliveryFailedLabel.Visible)
            DeliveryFailedLabel.Modulate = ErrorColor;

        // Reorder children only when the message side changes.
        if (_previousIsOwnMessage != isOwnMessage)
        {
            // For own messages: FlexSpace -> MessagePanel -> RightSpacer
            // For other messages: LeftSpacer -> MessagePanel -> FlexSpace
            MessageContainer.RemoveAllChildren();

            if (isOwnMessage)
            {
                MessageContainer.AddChild(FlexSpace);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(RightSpacer);
            }
            else
            {
                MessageContainer.AddChild(LeftSpacer);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(FlexSpace);
            }

            _previousIsOwnMessage = isOwnMessage;
        }
    }
}

