// SPDX-FileCopyrightText: 2024 Milon <milonpl.git@proton.me>
// SPDX-FileCopyrightText: 2024 Skubman <ba.fallaria@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2025 Tobias Berger <toby@tobot.dev>
// SPDX-FileCopyrightText: 2025 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.GameTicking.Managers;
using Content.Client._DV.CartridgeLoader.Cartridges;
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Timing;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragmentPirate : BoxContainer
{
    private static readonly TimeSpan SeparatorGap = TimeSpan.FromMinutes(1);
    private static readonly Color TimeSeparatorLineColor = Color.FromHex("#50597844");
    private static readonly Color TimeSeparatorTextColor = Color.FromHex("#9ca6c2");

    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    private readonly NewChatPopup _newChatPopup;
    private readonly ClientGameTicker _gameTicker;
    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;
    private Dictionary<uint, NanoChatRecipient> _recipients = new();
    private Dictionary<uint, List<NanoChatMessage>> _messages = new();
    private uint? _renderedChat;
    private readonly List<NanoChatMessage> _renderedMessages = new();
    private readonly List<RenderedMessageRow> _renderedRows = new();

    public event Action<NanoChatUiMessageType, uint?, string?, string?>? OnMessageSent;

    public NanoChatUiFragmentPirate()
    {
        IoCManager.InjectDependencies(this);
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        RobustXamlLoader.Load(this);

        _newChatPopup = new NewChatPopup();
        SetupEventHandlers();
    }

    private void SetupEventHandlers()
    {
        _newChatPopup.OnChatCreated += (number, name, job) =>
        {
            OnMessageSent?.Invoke(NanoChatUiMessageType.NewChat, number, name, job);
        };

        NewChatButton.OnPressed += _ =>
        {
            _newChatPopup.ClearInputs();
            _newChatPopup.OpenCentered();
        };

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleMute, null, null, null);
        };

        MessageInput.OnTextChanged += args =>
        {
            var length = args.Text.Length;
            var isValid = !string.IsNullOrWhiteSpace(args.Text) &&
                          length <= NanoChatMessage.MaxContentLength &&
                          (_currentChat != null || _pendingChat != null);

            SendButton.Disabled = !isValid;

            // Show character count when over limit
            var overLimit = length > NanoChatMessage.MaxContentLength;
            CharacterCount.Visible = overLimit;

            if (overLimit)
            {
                CharacterCount.StyleClasses.Clear();
                CharacterCount.StyleClasses.Add("LabelSubText");
                CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                    ("current", length),
                    ("max", NanoChatMessage.MaxContentLength));
                CharacterCount.StyleClasses.Add("LabelDanger");
            }
        };

        LookupButton.OnPressed += _ => ToggleView();
        LookupView.OnStartChat += contact =>
        {
            if (OnMessageSent is { } handler)
            {
                handler(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle);
                SelectChat(contact.Number);
                ToggleView();
            }
        };
        ListNumberButton.OnPressed += _ =>
        {
            _listNumber = !_listNumber;
            UpdateListNumber();
            OnMessageSent?.Invoke(NanoChatUiMessageType.ToggleListNumber, null, null, null);
        };

        MessageInput.OnTextEntered += _ => SendMessage(); // Send message when pressing enter
        SendButton.OnPressed += _ => SendMessage();
        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();
    }

    private void ToggleView()
    {
        ChatView.Visible = !ChatView.Visible;
        LookupView.Visible = !ChatView.Visible;
        LookupButton.Pressed = LookupView.Visible;
    }

    private void SendMessage()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null || string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        var messageContent = MessageInput.Text.Trim();
        if (messageContent.Length > NanoChatMessage.MaxContentLength)
            messageContent = messageContent[..NanoChatMessage.MaxContentLength];

        // Add predicted message
        var predictedMessage = new NanoChatMessage(
            _timing.CurTime,
            messageContent,
            _ownNumber
        );

        if (!_messages.TryGetValue(activeChat.Value, out var value))
            value = new List<NanoChatMessage>();

        var predictedMessages = new List<NanoChatMessage>(value)
        {
            predictedMessage
        };
        _messages[activeChat.Value] = predictedMessages;

        // Update UI with predicted message
        UpdateMessages(_messages);

        // Send message event
        OnMessageSent?.Invoke(NanoChatUiMessageType.SendMessage, activeChat, messageContent, null);

        // Clear input
        MessageInput.Text = string.Empty;
        SendButton.Disabled = true;
    }

    private void SelectChat(uint number)
    {
        // Don't reselect the same chat
        if (_currentChat == number && _pendingChat == null)
            return;

        _pendingChat = number;

        // Predict marking messages as read
        if (_recipients.TryGetValue(number, out var recipient))
        {
            recipient.HasUnread = false;
            _recipients[number] = recipient;
            UpdateChatList(_recipients);
        }

        OnMessageSent?.Invoke(NanoChatUiMessageType.SelectChat, number, null, null);
        UpdateCurrentChat();
    }

    private void DeleteCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        OnMessageSent?.Invoke(NanoChatUiMessageType.DeleteChat, activeChat, null, null);
    }

    private void UpdateChatList(Dictionary<uint, NanoChatRecipient> recipients)
    {
        foreach (var entry in ChatList.Children.OfType<NanoChatEntryPirate>())
        {
            entry.OnPressed -= SelectChat;
        }

        ChatList.RemoveAllChildren();
        _recipients = recipients;

        NoChatsLabel.Visible = recipients.Count == 0;
        NoChatsLabel.Parent?.RemoveChild(NoChatsLabel);
        ChatList.AddChild(NoChatsLabel);

        foreach (var (number, recipient) in recipients.OrderBy(r => r.Value.Name))
        {
            var entry = new NanoChatEntryPirate();
            // For pending chat selection, always show it as selected even if unconfirmed
            var isSelected = (_pendingChat == number) || (_pendingChat == null && _currentChat == number);
            entry.SetRecipient(recipient, number, isSelected);
            entry.OnPressed += SelectChat;
            ChatList.AddChild(entry);
        }
    }

    private void UpdateCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        var hasActiveChat = activeChat != null;

        // Update UI state
        MessagesScroll.Visible = hasActiveChat;
        CurrentChatName.Visible = hasActiveChat;
        MessageInputContainer.Visible = hasActiveChat;
        DeleteChatButton.Visible = hasActiveChat;
        DeleteChatButton.Disabled = !hasActiveChat;

        if (activeChat != null && _recipients.TryGetValue(activeChat.Value, out var recipient))
        {
            CurrentChatName.Text = recipient.Name + (string.IsNullOrEmpty(recipient.JobTitle) ? "" : $" ({recipient.JobTitle})");
        }
        else
        {
            CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");
        }
    }

    private void UpdateMessages(Dictionary<uint, List<NanoChatMessage>> messages)
    {
        _messages = messages;
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat != _renderedChat)
        {
            ClearRenderedMessages();
            _renderedChat = activeChat;
        }

        if (activeChat == null || !messages.TryGetValue(activeChat.Value, out var chatMessages))
        {
            if (_renderedRows.Count > 0)
                ClearRenderedMessages();

            return;
        }

        var previousCount = _renderedMessages.Count;
        var overlapCount = previousCount < chatMessages.Count ? previousCount : chatMessages.Count;
        var rebuildFrom = -1;

        for (var i = 0; i < overlapCount; i++)
        {
            var incoming = chatMessages[i];
            var rendered = _renderedMessages[i];
            if (rendered.Equals(incoming))
                continue;

            if (rendered.Timestamp == incoming.Timestamp)
            {
                _renderedRows[i].Bubble.SetMessage(incoming, incoming.SenderId == _ownNumber);
                _renderedMessages[i] = incoming;
                continue;
            }

            rebuildFrom = i;
            break;
        }

        if (rebuildFrom == -1 && chatMessages.Count < previousCount)
            rebuildFrom = chatMessages.Count;

        if (rebuildFrom != -1)
            RemoveRenderedTail(rebuildFrom);

        TimeSpan? previousStationTime = _renderedMessages.Count > 0
            ? GetStationTime(_renderedMessages[^1].Timestamp)
            : null;

        for (var i = _renderedMessages.Count; i < chatMessages.Count; i++)
        {
            previousStationTime = AddRenderedMessage(chatMessages[i], previousStationTime, SeparatorGap);
        }

        if (chatMessages.Count <= previousCount)
            return;

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();

        MessagesScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private TimeSpan GetStationTime(TimeSpan messageTimestamp)
    {
        var stationTime = messageTimestamp - _gameTicker.RoundStartTimeSpan;
        return stationTime < TimeSpan.Zero ? TimeSpan.Zero : stationTime;
    }

    private TimeSpan AddRenderedMessage(NanoChatMessage message, TimeSpan? previousStationTime, TimeSpan separatorGap)
    {
        var stationTime = GetStationTime(message.Timestamp);
        var shouldAddSeparator = previousStationTime == null || stationTime - previousStationTime.Value >= separatorGap;

        var row = new RenderedMessageRow();
        if (shouldAddSeparator)
        {
            var (topGap, separatorRow, bottomGap) = AddTimeSeparator(stationTime);
            row.SeparatorTopGap = topGap;
            row.SeparatorRow = separatorRow;
            row.SeparatorBottomGap = bottomGap;
        }

        var bubble = new NanoChatMessageBubblePirate();
        bubble.SetMessage(message, message.SenderId == _ownNumber);
        MessageList.AddChild(bubble);

        var spacing = new Control { MinSize = new Vector2(0, 6) };
        MessageList.AddChild(spacing);

        row.Bubble = bubble;
        row.Spacing = spacing;
        _renderedMessages.Add(message);
        _renderedRows.Add(row);
        return stationTime;
    }

    private void ClearRenderedMessages()
    {
        MessageList.RemoveAllChildren();
        _renderedMessages.Clear();
        _renderedRows.Clear();
    }

    private void RemoveRenderedTail(int startIndex)
    {
        for (var i = _renderedRows.Count - 1; i >= startIndex; i--)
        {
            var row = _renderedRows[i];
            row.SeparatorTopGap?.Parent?.RemoveChild(row.SeparatorTopGap);
            row.SeparatorRow?.Parent?.RemoveChild(row.SeparatorRow);
            row.SeparatorBottomGap?.Parent?.RemoveChild(row.SeparatorBottomGap);
            row.Bubble.Parent?.RemoveChild(row.Bubble);
            row.Spacing.Parent?.RemoveChild(row.Spacing);
        }

        _renderedRows.RemoveRange(startIndex, _renderedRows.Count - startIndex);
        _renderedMessages.RemoveRange(startIndex, _renderedMessages.Count - startIndex);
    }

    private (Control TopGap, BoxContainer SeparatorRow, Control BottomGap) AddTimeSeparator(TimeSpan stationTime)
    {
        var topGap = new Control { MinSize = new Vector2(0, 4) };
        MessageList.AddChild(topGap);

        var separatorRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        separatorRow.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            MaxSize = new Vector2(float.MaxValue, 1),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = TimeSeparatorLineColor
            }
        });

        separatorRow.AddChild(new Label
        {
            Text = stationTime.ToString(@"hh\:mm\:ss"),
            Margin = new Thickness(12, 0, 12, 0),
            StyleClasses = { "LabelSubText" },
            ModulateSelfOverride = TimeSeparatorTextColor
        });

        separatorRow.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            MaxSize = new Vector2(float.MaxValue, 1),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = TimeSeparatorLineColor
            }
        });

        MessageList.AddChild(separatorRow);
        var bottomGap = new Control { MinSize = new Vector2(0, 6) };
        MessageList.AddChild(bottomGap);
        return (topGap, separatorRow, bottomGap);
    }

    // RenderedMessageRow invariant: Bubble and Spacing are assigned in AddRenderedMessage
    // before the row is inserted into _renderedRows, so these default! fields are non-null at runtime.
    private sealed class RenderedMessageRow
    {
        public Control? SeparatorTopGap;
        public BoxContainer? SeparatorRow;
        public Control? SeparatorBottomGap;
        public NanoChatMessageBubblePirate Bubble = default!;
        public Control Spacing = default!;
    }

    private void UpdateMuteButton()
    {
        if (BellMutedIcon != null)
            BellMutedIcon.Visible = _notificationsMuted;

        if (BellIcon != null)
            BellIcon.Visible = !_notificationsMuted;
    }

    private void UpdateListNumber()
    {
        if (ListNumberButton != null)
            ListNumberButton.Pressed = _listNumber;
    }

    public void UpdateState(NanoChatUiState state)
    {
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";
        UpdateMuteButton();
        UpdateListNumber();

        // Update new chat button state based on recipient limit
        var atLimit = state.Recipients.Count >= state.MaxRecipients;
        NewChatButton.Disabled = atLimit;
        NewChatButton.ToolTip = atLimit
            ? Loc.GetString("nano-chat-max-recipients")
            : Loc.GetString("nano-chat-new-chat");

        // Clear any local prediction once server state arrives.
        _pendingChat = null;

        // Server state is authoritative for selected chat.
        _currentChat = state.CurrentChat;

        UpdateCurrentChat();
        UpdateChatList(state.Recipients);
        UpdateMessages(state.Messages);
        LookupView.UpdateContactList(state);
    }
}

