using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;
using Robust.Shared.Utility;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBubblePirate : BoxContainer
{
    public static readonly Color OwnMessageColor = Color.FromHex("#1f402fd9");
    public static readonly Color OtherMessageColor = Color.FromHex("#3b4258f0");
    public static readonly Color TextColor = Color.FromHex("#e1e6f0");
    public static readonly Color ErrorColor = Color.FromHex("#cc3333");
    private bool? _previousIsOwnMessage;
    private uint? _previousMessageId;
    private (uint Id, bool HasPhoto, int PreviewSignature, int ImageSignature)? _previousMessageSignature;

    public event Action<uint>? OnStorePhotoPressed;

    public NanoChatMessageBubblePirate()
    {
        RobustXamlLoader.Load(this);
        MessageText.Modulate = TextColor;
        DeliveryFailedLabel.HorizontalAlignment = HAlignment.Right;
        PhotoNameLabel.ModulateSelfOverride = TextColor.WithAlpha(0.8f);
        StorePhotoButton.OnPressed += _ =>
        {
            if (_previousMessageId != null)
                OnStorePhotoPressed?.Invoke(_previousMessageId.Value);
        };
    }

    public void SetMessage(NanoChatMessage message, bool isOwnMessage)
    {
        if (MessagePanel.PanelOverride is not StyleBoxFlat style)
            return;

        // Configure message appearance
        style.BackgroundColor = isOwnMessage ? OwnMessageColor : OtherMessageColor;
        style.BorderThickness = new Thickness(0);

        // Set message content
        var hasText = !string.IsNullOrWhiteSpace(message.Content);
        MessageText.Visible = hasText;
        MessageText.Text = hasText ? message.Content : string.Empty;

        var hasPhoto = message.Photo != null;
        PhotoNameLabel.Visible = hasPhoto;
        PhotoNameLabel.Text = hasPhoto ? message.Photo!.Value.FileName : string.Empty;
        StorePhotoButton.Visible = hasPhoto && !isOwnMessage;
        StorePhotoButton.Disabled = !StorePhotoButton.Visible;
        StorePhotoButton.ToolTip = StorePhotoButton.Visible
            ? Loc.GetString("nano-chat-store-photo")
            : null;

        var messageSignature = (
            message.Id,
            message.HasPhoto,
            ComputePhotoDataSignature(message.Photo?.PreviewData),
            ComputePhotoDataSignature(message.Photo?.ImageData));

        if (_previousMessageSignature != messageSignature)
        {
            ApplyPhotoPreview(message);
            _previousMessageSignature = messageSignature;
        }

        _previousMessageId = message.Id;

        // Show delivery failed text if needed (only for own messages)
        DeliveryFailedLabel.Visible = isOwnMessage && message.DeliveryFailed;
        if (DeliveryFailedLabel.Visible)
            DeliveryFailedLabel.Modulate = ErrorColor;

        // Reorder children only when the message side changes.
        if (_previousIsOwnMessage != isOwnMessage)
        {
            // For own messages: FlexSpace -> MessagePanel -> RightSpacer
            // For other messages: LeftSpacer -> MessagePanel -> FlexSpace
            MessageContainer.RemoveAllChildren();

            if (isOwnMessage)
            {
                MessageContainer.AddChild(FlexSpace);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(RightSpacer);
            }
            else
            {
                MessageContainer.AddChild(LeftSpacer);
                MessageContainer.AddChild(MessageBox);
                MessageContainer.AddChild(FlexSpace);
            }

            _previousIsOwnMessage = isOwnMessage;
        }
    }

    private void ApplyPhotoPreview(NanoChatMessage message)
    {
        PhotoPreview.Texture = null;
        PhotoPreview.Visible = false;

        if (message.Photo is not { } photo)
            return;

        var data = photo.ImageData is { Length: > 0 } imageData
            ? imageData
            : photo.PreviewData;

        if (data is not { Length: > 0 })
            return;

        try
        {
            using var stream = new MemoryStream(data);
            PhotoPreview.Texture = Texture.LoadFromPNGStream(stream, $"nanochat-photo-{message.Id}");
            if (PhotoPreview.Texture != null)
            {
                const float maxWidth = 258f;
                const float maxHeight = 258f;
                var textureWidth = PhotoPreview.Texture.Size.X;
                var textureHeight = PhotoPreview.Texture.Size.Y;
                if (textureWidth > 0f && textureHeight > 0f)
                {
                    var scale = MathF.Min(maxWidth / textureWidth, maxHeight / textureHeight);
                    var scaledWidth = textureWidth * scale;
                    var scaledHeight = textureHeight * scale;
                    PhotoPreview.SetSize = new Vector2(scaledWidth, scaledHeight);
                }
                else
                {
                    PhotoPreview.SetSize = new Vector2(96f, 96f);
                }
            }
            PhotoPreview.Visible = PhotoPreview.Texture != null;
        }
        catch (Exception ex)
        {
            Logger.Warning($"Failed to load NanoChat photo preview for message {message.Id}: {ex}");
            PhotoPreview.Texture = null;
            PhotoPreview.Visible = false;
        }
    }

    private static int ComputePhotoDataSignature(byte[]? data)
    {
        if (data is not { Length: > 0 })
            return 0;

        var length = data.Length;
        var first = data[0];
        var quarter = data[length / 4];
        var middle = data[length / 2];
        var threeQuarter = data[(length * 3) / 4];
        var last = data[length - 1];
        return HashCode.Combine(length, first, quarter, middle, threeQuarter, last);
    }
}

