using System.IO;
using System.Linq;
using System.Numerics;
using System;
using Content.Client.GameTicking.Managers;
using Content.Client._DV.CartridgeLoader.Cartridges;
using Content.Client.Stylesheets;
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragmentPirate : BoxContainer
{
    private enum NanoChatViewMode : byte
    {
        Chat,
        Lookup,
        Gallery,
        GalleryPick,
    }

    private static readonly TimeSpan SeparatorGap = TimeSpan.FromMinutes(1);
    private static readonly Color TimeSeparatorLineColor = Color.FromHex("#50597844");
    private static readonly Color TimeSeparatorTextColor = Color.FromHex("#9ca6c2");
    private const int PhotoLabelFontSize = 12;
    private const int GalleryPreviewTitleMaxChars = 28;
    private const int AttachedPhotoTitleMaxChars = 24;
    private const float GalleryPreviewFallbackWidth = 320f;
    private const float GalleryPreviewPadding = 6f;

    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly NewChatPopup _newChatPopup;
    private readonly ClientGameTicker _gameTicker;
    private uint? _currentChat;
    private uint? _pendingChat;
    private uint _ownNumber;
    private bool _notificationsMuted;
    private bool _listNumber = true;
    private NanoChatViewMode _viewMode = NanoChatViewMode.Chat;
    private Dictionary<uint, NanoChatRecipient> _recipients = new();
    private Dictionary<uint, List<NanoChatMessage>> _messages = new();
    private Dictionary<string, NanoChatPhotoData> _photos = new();
    private uint? _renderedChat;
    private readonly List<NanoChatMessage> _renderedMessages = new();
    private readonly List<RenderedMessageRow> _renderedRows = new();
    private string? _selectedGalleryPhotoFileName;
    private string? _attachedPhotoFileName;

    public event Action<NanoChatUiMessageEvent>? OnMessageSent;

    public NanoChatUiFragmentPirate()
    {
        IoCManager.InjectDependencies(this);
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        RobustXamlLoader.Load(this);
        GalleryPreviewName.FontOverride = _resourceCache.NotoStack(size: PhotoLabelFontSize);
        AttachmentLabel.FontOverride = _resourceCache.NotoStack(size: PhotoLabelFontSize);

        _newChatPopup = new NewChatPopup();
        SetupEventHandlers();
        SetViewMode(NanoChatViewMode.Chat);
        UpdateAttachmentIndicator();
    }

    private void SetupEventHandlers()
    {
        _newChatPopup.OnChatCreated += (number, name, job) =>
        {
            EmitMessage(NanoChatUiMessageType.NewChat, number, name, job);
        };

        NewChatButton.OnPressed += _ =>
        {
            _newChatPopup.ClearInputs();
            _newChatPopup.OpenCentered();
        };

        MuteButton.OnPressed += _ =>
        {
            _notificationsMuted = !_notificationsMuted;
            UpdateMuteButton();
            EmitMessage(NanoChatUiMessageType.ToggleMute);
        };

        LookupButton.OnPressed += _ =>
        {
            SetViewMode(_viewMode == NanoChatViewMode.Lookup
                ? NanoChatViewMode.Chat
                : NanoChatViewMode.Lookup);
        };

        GalleryButton.OnPressed += _ =>
        {
            switch (_viewMode)
            {
                case NanoChatViewMode.Chat:
                case NanoChatViewMode.Lookup:
                    SetViewMode(NanoChatViewMode.Gallery);
                    break;
                case NanoChatViewMode.Gallery:
                case NanoChatViewMode.GalleryPick:
                    SetViewMode(NanoChatViewMode.Chat);
                    break;
            }
        };

        LookupView.OnStartChat += contact =>
        {
            EmitMessage(NanoChatUiMessageType.NewChat, contact.Number, contact.Name, contact.JobTitle);
            SelectChat(contact.Number);
            SetViewMode(NanoChatViewMode.Chat);
        };

        ListNumberButton.OnPressed += _ =>
        {
            _listNumber = !_listNumber;
            UpdateListNumber();
            EmitMessage(NanoChatUiMessageType.ToggleListNumber);
        };

        MessageInput.OnTextChanged += args =>
        {
            var length = args.Text.Length;
            var overLimit = length > NanoChatMessage.MaxContentLength;
            CharacterCount.Visible = overLimit;

            if (overLimit)
            {
                CharacterCount.StyleClasses.Clear();
                CharacterCount.StyleClasses.Add("LabelSubText");
                CharacterCount.StyleClasses.Add("LabelDanger");
                CharacterCount.Text = Loc.GetString("nano-chat-message-too-long",
                    ("current", length),
                    ("max", NanoChatMessage.MaxContentLength));
            }

            UpdateComposeState();
        };

        MessageInput.OnTextEntered += _ => SendMessage();
        SendButton.OnPressed += _ => SendMessage();
        DeleteChatButton.OnPressed += _ => DeleteCurrentChat();

        AttachmentButton.OnPressed += _ =>
        {
            if ((_pendingChat ?? _currentChat) != null)
                SetViewMode(NanoChatViewMode.GalleryPick);
        };

        RemoveAttachmentButton.OnPressed += _ =>
        {
            _attachedPhotoFileName = null;
            UpdateAttachmentIndicator();
            UpdateComposeState();
        };

        GalleryActionButton.OnPressed += _ => AttachSelectedGalleryPhoto();
        GalleryDeleteButton.OnPressed += _ => DeleteSelectedGalleryPhoto();
        GalleryPreviewScroll.OnResized += RefreshGalleryPreviewSize;
    }

    private void EmitMessage(
        NanoChatUiMessageType type,
        uint? recipientNumber = null,
        string? content = null,
        string? recipientJob = null,
        string? photoFileName = null,
        uint? messageId = null)
    {
        OnMessageSent?.Invoke(new NanoChatUiMessageEvent(
            type,
            recipientNumber,
            content,
            recipientJob,
            photoFileName,
            messageId));
    }

    private void SetSelectedGalleryPhoto(string? fileName, bool notifyServer = true)
    {
        if (_selectedGalleryPhotoFileName == fileName)
            return;

        _selectedGalleryPhotoFileName = fileName;

        if (notifyServer)
            EmitMessage(NanoChatUiMessageType.SelectGalleryPhoto, photoFileName: fileName);
    }

    private void SetViewMode(NanoChatViewMode mode)
    {
        if (mode == NanoChatViewMode.GalleryPick && (_pendingChat ?? _currentChat) == null)
            mode = NanoChatViewMode.Chat;

        _viewMode = mode;
        ChatView.Visible = mode == NanoChatViewMode.Chat;
        LookupView.Visible = mode == NanoChatViewMode.Lookup;
        GalleryView.Visible = mode is NanoChatViewMode.Gallery or NanoChatViewMode.GalleryPick;
        LookupButton.Pressed = mode == NanoChatViewMode.Lookup;
        UpdateGalleryToggleButton();
        UpdateCurrentChat();
        UpdateGalleryPreview();
    }

    private void UpdateGalleryToggleButton()
    {
        GalleryButton.Text = _viewMode switch
        {
            NanoChatViewMode.Gallery => Loc.GetString("nano-chat-go-to-chat"),
            NanoChatViewMode.GalleryPick => Loc.GetString("nano-chat-back"),
            _ => Loc.GetString("nano-chat-go-to-gallery"),
        };
        GalleryButton.ToolTip = GalleryButton.Text;
    }

    private void UpdateComposeState()
    {
        var activeChat = _pendingChat ?? _currentChat;
        var text = MessageInput.Text;
        var hasText = !string.IsNullOrWhiteSpace(text);
        var hasAttachment = _attachedPhotoFileName != null;
        var isWithinLimit = text.Length <= NanoChatMessage.MaxContentLength;

        SendButton.Disabled = activeChat == null || !isWithinLimit || (!hasText && !hasAttachment);
        AttachmentButton.Disabled = activeChat == null;
    }

    private void SendMessage()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        var messageContent = MessageInput.Text.Trim();
        if (messageContent.Length > NanoChatMessage.MaxContentLength)
            messageContent = messageContent[..NanoChatMessage.MaxContentLength];

        NanoChatPhotoData? attachment = null;
        if (_attachedPhotoFileName is { } photoFileName &&
            _photos.TryGetValue(photoFileName, out var selectedPhoto))
        {
            attachment = selectedPhoto;
        }

        if (string.IsNullOrWhiteSpace(messageContent) && attachment == null)
            return;

        var predictedMessage = new NanoChatMessage(
            0,
            _timing.CurTime,
            messageContent,
            _ownNumber,
            photo: attachment);

        if (!_messages.TryGetValue(activeChat.Value, out var value))
            value = new List<NanoChatMessage>();

        var predictedMessages = new List<NanoChatMessage>(value)
        {
            predictedMessage
        };
        _messages[activeChat.Value] = predictedMessages;
        UpdateMessages(_messages);

        EmitMessage(
            NanoChatUiMessageType.SendMessage,
            activeChat,
            messageContent,
            photoFileName: _attachedPhotoFileName);

        MessageInput.Text = string.Empty;
        _attachedPhotoFileName = null;
        UpdateAttachmentIndicator();
        UpdateComposeState();
    }

    private void SelectChat(uint number)
    {
        if (_currentChat == number && _pendingChat == null)
            return;

        _pendingChat = number;

        if (_recipients.TryGetValue(number, out var recipient))
        {
            recipient.HasUnread = false;
            _recipients[number] = recipient;
            UpdateChatList(_recipients);
        }

        UpdateMessages(_messages);
        EmitMessage(NanoChatUiMessageType.SelectChat, number);
        UpdateCurrentChat();
    }

    private void DeleteCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        EmitMessage(NanoChatUiMessageType.DeleteChat, activeChat);
    }

    private void UpdateChatList(Dictionary<uint, NanoChatRecipient> recipients)
    {
        foreach (var entry in ChatList.Children.OfType<NanoChatEntryPirate>())
        {
            entry.OnPressed -= SelectChat;
        }

        ChatList.RemoveAllChildren();
        _recipients = recipients;

        NoChatsLabel.Visible = recipients.Count == 0;
        NoChatsLabel.Parent?.RemoveChild(NoChatsLabel);
        ChatList.AddChild(NoChatsLabel);

        foreach (var (number, recipient) in recipients.OrderBy(r => r.Value.Name))
        {
            var entry = new NanoChatEntryPirate();
            var isSelected = (_pendingChat == number) || (_pendingChat == null && _currentChat == number);
            entry.SetRecipient(recipient, number, isSelected);
            entry.OnPressed += SelectChat;
            ChatList.AddChild(entry);
        }
    }

    private void UpdateCurrentChat()
    {
        var activeChat = _pendingChat ?? _currentChat;
        var hasActiveChat = activeChat != null;

        MessagesScroll.Visible = hasActiveChat && _viewMode == NanoChatViewMode.Chat;
        CurrentChatName.Visible = _viewMode == NanoChatViewMode.Chat && !hasActiveChat;
        MessageInputContainer.Visible = hasActiveChat && _viewMode == NanoChatViewMode.Chat;
        DeleteChatButton.Visible = hasActiveChat && _viewMode == NanoChatViewMode.Chat;
        DeleteChatButton.Disabled = !hasActiveChat;

        if (activeChat != null && _recipients.TryGetValue(activeChat.Value, out var recipient))
        {
            CurrentChatName.Text = recipient.Name + (string.IsNullOrEmpty(recipient.JobTitle) ? string.Empty : $" ({recipient.JobTitle})");
        }
        else
        {
            CurrentChatName.Text = Loc.GetString("nano-chat-select-chat");
        }

        UpdateComposeState();
    }

    private void UpdateMessages(Dictionary<uint, List<NanoChatMessage>> messages)
    {
        _messages = messages;
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat != _renderedChat)
        {
            ClearRenderedMessages();
            _renderedChat = activeChat;
        }

        if (activeChat == null || !messages.TryGetValue(activeChat.Value, out var chatMessages))
        {
            if (_renderedRows.Count > 0)
                ClearRenderedMessages();

            return;
        }

        var previousCount = _renderedMessages.Count;
        var overlapCount = previousCount < chatMessages.Count ? previousCount : chatMessages.Count;
        var rebuildFrom = -1;

        for (var i = 0; i < overlapCount; i++)
        {
            var incoming = chatMessages[i];
            var rendered = _renderedMessages[i];
            if (rendered.Equals(incoming))
                continue;

            if (rendered.Timestamp == incoming.Timestamp)
            {
                _renderedRows[i].Bubble.SetMessage(incoming, incoming.SenderId == _ownNumber);
                _renderedMessages[i] = incoming;
                continue;
            }

            rebuildFrom = i;
            break;
        }

        if (rebuildFrom == -1 && chatMessages.Count < previousCount)
            rebuildFrom = chatMessages.Count;

        if (rebuildFrom != -1)
            RemoveRenderedTail(rebuildFrom);

        TimeSpan? previousStationTime = _renderedMessages.Count > 0
            ? GetStationTime(_renderedMessages[^1].Timestamp)
            : null;

        for (var i = _renderedMessages.Count; i < chatMessages.Count; i++)
        {
            previousStationTime = AddRenderedMessage(chatMessages[i], previousStationTime, SeparatorGap);
        }

        if (chatMessages.Count <= previousCount)
            return;

        MessageList.InvalidateMeasure();
        MessagesScroll.InvalidateMeasure();
        MessagesScroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private TimeSpan GetStationTime(TimeSpan messageTimestamp)
    {
        var stationTime = messageTimestamp - _gameTicker.RoundStartTimeSpan;
        return stationTime < TimeSpan.Zero ? TimeSpan.Zero : stationTime;
    }

    private TimeSpan AddRenderedMessage(NanoChatMessage message, TimeSpan? previousStationTime, TimeSpan separatorGap)
    {
        var stationTime = GetStationTime(message.Timestamp);
        var shouldAddSeparator = previousStationTime == null || stationTime - previousStationTime.Value >= separatorGap;

        var row = new RenderedMessageRow();
        if (shouldAddSeparator)
        {
            var (topGap, separatorRow, bottomGap) = AddTimeSeparator(stationTime);
            row.SeparatorTopGap = topGap;
            row.SeparatorRow = separatorRow;
            row.SeparatorBottomGap = bottomGap;
        }

        var bubble = new NanoChatMessageBubblePirate();
        bubble.SetMessage(message, message.SenderId == _ownNumber);
        bubble.OnStorePhotoPressed += HandleStorePhotoPressed;
        MessageList.AddChild(bubble);

        var spacing = new Control { MinSize = new Vector2(0, 6) };
        MessageList.AddChild(spacing);

        row.Bubble = bubble;
        row.Spacing = spacing;
        _renderedMessages.Add(message);
        _renderedRows.Add(row);
        return stationTime;
    }

    private void HandleStorePhotoPressed(uint messageId)
    {
        var activeChat = _pendingChat ?? _currentChat;
        if (activeChat == null)
            return;

        EmitMessage(
            NanoChatUiMessageType.StoreMessagePhoto,
            activeChat,
            messageId: messageId);
    }

    private void ClearRenderedMessages()
    {
        MessageList.RemoveAllChildren();
        _renderedMessages.Clear();
        _renderedRows.Clear();
    }

    private void RemoveRenderedTail(int startIndex)
    {
        for (var i = _renderedRows.Count - 1; i >= startIndex; i--)
        {
            var row = _renderedRows[i];
            row.SeparatorTopGap?.Parent?.RemoveChild(row.SeparatorTopGap);
            row.SeparatorRow?.Parent?.RemoveChild(row.SeparatorRow);
            row.SeparatorBottomGap?.Parent?.RemoveChild(row.SeparatorBottomGap);
            row.Bubble.Parent?.RemoveChild(row.Bubble);
            row.Spacing.Parent?.RemoveChild(row.Spacing);
        }

        _renderedRows.RemoveRange(startIndex, _renderedRows.Count - startIndex);
        _renderedMessages.RemoveRange(startIndex, _renderedMessages.Count - startIndex);
    }

    private (Control TopGap, BoxContainer SeparatorRow, Control BottomGap) AddTimeSeparator(TimeSpan stationTime)
    {
        var topGap = new Control { MinSize = new Vector2(0, 4) };
        MessageList.AddChild(topGap);

        var separatorRow = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        separatorRow.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            MaxSize = new Vector2(float.MaxValue, 1),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = TimeSeparatorLineColor
            }
        });

        separatorRow.AddChild(new Label
        {
            Text = stationTime.ToString(@"hh\:mm\:ss"),
            Margin = new Thickness(12, 0, 12, 0),
            StyleClasses = { "LabelSubText" },
            ModulateSelfOverride = TimeSeparatorTextColor
        });

        separatorRow.AddChild(new PanelContainer
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(0, 1),
            MaxSize = new Vector2(float.MaxValue, 1),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = TimeSeparatorLineColor
            }
        });

        MessageList.AddChild(separatorRow);
        var bottomGap = new Control { MinSize = new Vector2(0, 6) };
        MessageList.AddChild(bottomGap);
        return (topGap, separatorRow, bottomGap);
    }

    private void UpdateGalleryList()
    {
        GalleryList.RemoveAllChildren();

        EnsureSelectedGalleryPhoto();

        NoGalleryPhotosLabel.Visible = _photos.Count == 0;
        NoGalleryPhotosLabel.Parent?.RemoveChild(NoGalleryPhotosLabel);
        GalleryList.AddChild(NoGalleryPhotosLabel);

        foreach (var fileName in _photos.Keys.OrderBy(name => name))
        {
            var entry = new NanoChatEntryPirate();
            entry.SetGalleryItem(fileName, 0, fileName == _selectedGalleryPhotoFileName);
            entry.OnPressed += _ =>
            {
                SetSelectedGalleryPhoto(fileName);
                UpdateGalleryList();
                UpdateGalleryPreview();
            };

            GalleryList.AddChild(entry);
        }
    }

    private void EnsureSelectedGalleryPhoto()
    {
        if (_attachedPhotoFileName != null && !_photos.ContainsKey(_attachedPhotoFileName))
        {
            _attachedPhotoFileName = null;
            UpdateAttachmentIndicator();
        }

        if (_selectedGalleryPhotoFileName != null && _photos.ContainsKey(_selectedGalleryPhotoFileName))
            return;

        SetSelectedGalleryPhoto(_photos.Keys.OrderBy(name => name).FirstOrDefault());
    }

    private void UpdateGalleryPreview()
    {
        var hasSelectedPhoto = false;
        var selectedPhoto = default(NanoChatPhotoData);
        if (_selectedGalleryPhotoFileName != null &&
            _photos.TryGetValue(_selectedGalleryPhotoFileName, out var foundPhoto))
        {
            hasSelectedPhoto = true;
            selectedPhoto = foundPhoto;
        }

        var selectedPhotoFileName = selectedPhoto.FileName ?? string.Empty;
        GalleryPreviewName.Text = hasSelectedPhoto
            ? TruncateLabelText(selectedPhotoFileName, GalleryPreviewTitleMaxChars)
            : string.Empty;
        GalleryPreviewName.ToolTip = hasSelectedPhoto ? selectedPhotoFileName : null;
        GalleryPreviewName.Visible = true;
        GalleryPreviewHeader.Visible = hasSelectedPhoto;
        GalleryEmptyLabel.Visible = !hasSelectedPhoto;
        GalleryPreviewScroll.Visible = false;
        GalleryPreviewImage.Visible = false;
        GalleryPreviewImage.Texture = null;
        GalleryPreviewImage.SetSize = Vector2.Zero;

        if (hasSelectedPhoto)
        {
            var texture = LoadTexture(
                selectedPhoto.ImageData is { Length: > 0 } ? selectedPhoto.ImageData : selectedPhoto.PreviewData,
                $"nanochat-gallery-{selectedPhoto.FileName}");
            ApplyGalleryPreviewTexture(texture);
            GalleryEmptyLabel.Visible = !GalleryPreviewImage.Visible;
        }

        GalleryActionButton.Visible = hasSelectedPhoto && _viewMode == NanoChatViewMode.GalleryPick;
        GalleryActionButton.Text = "+";
        GalleryDeleteButton.Visible = hasSelectedPhoto;
    }

    private void AttachSelectedGalleryPhoto()
    {
        if (_selectedGalleryPhotoFileName == null || !_photos.ContainsKey(_selectedGalleryPhotoFileName))
            return;

        _attachedPhotoFileName = _selectedGalleryPhotoFileName;
        UpdateAttachmentIndicator();
        UpdateComposeState();
        SetViewMode(NanoChatViewMode.Chat);
    }

    private void DeleteSelectedGalleryPhoto()
    {
        if (_selectedGalleryPhotoFileName == null)
            return;

        var deletedFileName = _selectedGalleryPhotoFileName;
        EmitMessage(NanoChatUiMessageType.DeleteGalleryPhoto, photoFileName: deletedFileName);
        _photos.Remove(deletedFileName);
        if (_attachedPhotoFileName == deletedFileName)
            _attachedPhotoFileName = null;

        _selectedGalleryPhotoFileName = null;
        UpdateAttachmentIndicator();
        UpdateComposeState();
        UpdateGalleryList();
        UpdateGalleryPreview();
    }

    private void UpdateAttachmentIndicator()
    {
        var hasAttachment = _attachedPhotoFileName != null;
        AttachmentBanner.Visible = hasAttachment;
        AttachmentLabel.Text = hasAttachment
            ? Loc.GetString("nano-chat-attached-photo",
                ("fileName", TruncateLabelText(_attachedPhotoFileName!, AttachedPhotoTitleMaxChars)))
            : string.Empty;
        AttachmentLabel.ToolTip = hasAttachment ? _attachedPhotoFileName : null;
    }

    private static Texture? LoadTexture(byte[]? data, string cacheKey)
    {
        if (data is not { Length: > 0 })
            return null;

        try
        {
            using var stream = new MemoryStream(data);
            return Texture.LoadFromPNGStream(stream, cacheKey);
        }
        catch
        {
            return null;
        }
    }

    private void ApplyGalleryPreviewTexture(Texture? texture)
    {
        GalleryPreviewImage.Texture = texture;
        GalleryPreviewImage.Visible = texture != null;
        GalleryPreviewScroll.Visible = texture != null;

        if (texture == null)
        {
            GalleryPreviewImage.SetSize = Vector2.Zero;
            return;
        }

        var maxWidth = MathF.Max(
            GalleryPreviewFallbackWidth,
            GalleryPreviewScroll.Width - GalleryPreviewPadding);
        var width = texture.Size.X;
        var height = texture.Size.Y;
        if (width <= 0f || height <= 0f)
        {
            GalleryPreviewImage.SetSize = new Vector2(maxWidth, maxWidth);
            return;
        }

        var scale = maxWidth / width;
        GalleryPreviewImage.SetSize = new Vector2(maxWidth, height * scale);
    }

    private void RefreshGalleryPreviewSize()
    {
        if (GalleryPreviewImage.Texture == null)
            return;

        ApplyGalleryPreviewTexture(GalleryPreviewImage.Texture);
    }

    private static string TruncateLabelText(string value, int maxChars)
    {
        if (value.Length <= maxChars)
            return value;

        if (maxChars <= 3)
            return value[..maxChars];

        return value[..(maxChars - 3)] + "...";
    }

    private void UpdateMuteButton()
    {
        BellMutedIcon.Visible = _notificationsMuted;
        BellIcon.Visible = !_notificationsMuted;
    }

    private void UpdateListNumber()
    {
        ListNumberButton.Pressed = _listNumber;
    }

    public void UpdateState(NanoChatUiState state)
    {
        _ownNumber = state.OwnNumber;
        _notificationsMuted = state.NotificationsMuted;
        _listNumber = state.ListNumber;
        _photos = new Dictionary<string, NanoChatPhotoData>(state.Photos);
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";
        UpdateMuteButton();
        UpdateListNumber();

        var atLimit = state.Recipients.Count >= state.MaxRecipients;
        NewChatButton.Disabled = atLimit;
        NewChatButton.ToolTip = atLimit
            ? Loc.GetString("nano-chat-max-recipients")
            : Loc.GetString("nano-chat-new-chat");

        _pendingChat = null;
        _currentChat = state.CurrentChat;
        if (_viewMode == NanoChatViewMode.GalleryPick && _currentChat == null)
            SetViewMode(NanoChatViewMode.Chat);

        UpdateCurrentChat();
        UpdateChatList(state.Recipients);
        UpdateMessages(state.Messages);
        UpdateGalleryList();
        UpdateGalleryPreview();
        UpdateAttachmentIndicator();
        UpdateComposeState();
        LookupView.UpdateContactList(state);
    }

    private sealed class RenderedMessageRow
    {
        public Control? SeparatorTopGap;
        public BoxContainer? SeparatorRow;
        public Control? SeparatorBottomGap;
        public NanoChatMessageBubblePirate Bubble = default!;
        public Control Spacing = default!;
    }
}
