using System.Numerics;
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Pirate.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntryPirate : BoxContainer
{
    private const float DefaultEntryWidth = 158f;
    private const float GalleryEntryWidth = 182f;
    private const float EntryHeight = 44f;
    private const int NameMaxChars = 16;
    private const int JobMaxChars = 20;
    private const int GalleryLineOneMaxChars = 17;
    private const int GalleryLineTwoMaxChars = 19;
    private static readonly Thickness ChatNameLabelMargin = new(0, -2, 0, 0);
    private static readonly Thickness GalleryNameLabelMargin = new(0, -1, 0, 0);
    private static readonly Color SelectedEntryColor = Color.FromHex("#4d5478d9");
    private static readonly Color UnreadIndicatorColor = Color.FromHex("#28d93e");
    private static readonly Color ActiveIndicatorColor = Color.FromHex("#7ea2ff");
    private static readonly Color HiddenIndicatorColor = Color.Transparent;

    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    public NanoChatEntryPirate()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected)
    {
        SetupPressHandler(number);
        SetEntryWidth(DefaultEntryWidth);
        NameLabel.Margin = ChatNameLabelMargin;

        NameLabel.Text = TruncateForEntry(recipient.Name, NameMaxChars) ?? string.Empty;
        NameLabel.ToolTip = recipient.Name;
        JobLabel.ModulateSelfOverride = null;

        var jobTitle = recipient.JobTitle ?? string.Empty;
        JobLabel.Text = TruncateForEntry(jobTitle, JobMaxChars) ?? string.Empty;
        JobLabel.ToolTip = jobTitle;
        JobLabel.Visible = !string.IsNullOrWhiteSpace(jobTitle);
        UnreadIndicator.Visible = true;
        if (UnreadIndicator.PanelOverride is StyleBoxFlat indicatorStyle)
        {
            var indicatorColor = recipient.HasUnread
                ? UnreadIndicatorColor
                : isSelected
                    ? ActiveIndicatorColor
                    : HiddenIndicatorColor;
            indicatorStyle.BackgroundColor = indicatorColor;
            indicatorStyle.BorderColor = indicatorColor;
        }

        ChatButton.ModulateSelfOverride = isSelected ? SelectedEntryColor : null;
    }

    public void SetGalleryItem(string fileName, uint index, bool isSelected)
    {
        SetupPressHandler(index);
        SetEntryWidth(GalleryEntryWidth);
        NameLabel.Margin = GalleryNameLabelMargin;

        NameLabel.Text = BuildGalleryLabel(fileName) ?? string.Empty;
        NameLabel.ToolTip = fileName;
        JobLabel.Text = string.Empty;
        JobLabel.ToolTip = null;
        JobLabel.ModulateSelfOverride = null;
        JobLabel.Visible = false;
        UnreadIndicator.Visible = true;
        if (UnreadIndicator.PanelOverride is StyleBoxFlat indicatorStyle)
        {
            var indicatorColor = isSelected ? ActiveIndicatorColor : HiddenIndicatorColor;
            indicatorStyle.BackgroundColor = indicatorColor;
            indicatorStyle.BorderColor = indicatorColor;
        }

        ChatButton.ModulateSelfOverride = isSelected ? SelectedEntryColor : null;
    }

    private void SetEntryWidth(float width)
    {
        var size = new Vector2(width, EntryHeight);
        ChatButton.MinSize = size;
        ChatButton.MaxSize = size;
    }

    private void SetupPressHandler(uint number)
    {
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;
    }

    private static string? BuildGalleryLabel(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        if (value.Length <= GalleryLineOneMaxChars)
            return value;

        var firstLine = value[..GalleryLineOneMaxChars];
        var remaining = value[GalleryLineOneMaxChars..];
        var secondLine = TruncateForEntry(remaining, GalleryLineTwoMaxChars) ?? string.Empty;
        return string.IsNullOrEmpty(secondLine)
            ? firstLine
            : $"{firstLine}\n{secondLine}";
    }

    private static string? TruncateForEntry(string? value, int maxChars)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        if (value.Length <= maxChars)
            return value;

        if (maxChars <= 3)
            return value[..maxChars];

        return value[..(maxChars - 3)] + "...";
    }
}

