using System.Numerics;
using Content.Client.Stylesheets;
using Content.Pirate.Shared.Vampire;
using Content.Pirate.Shared.Vampire.Components;
using Content.Client.Resources;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Pirate.Client.Vampire;

[GenerateTypedNameReferences]
public sealed partial class VampireMutationMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private IResourceCache _resourceCache;
    private readonly SpriteSystem _sprite;
    public event Action<VampireMutationsType>? OnIdSelected;

    private HashSet<VampireMutationsType> _possibleMutations = new();
    private VampireMutationsType _selectedId;

    public VampireMutationMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();
        _resourceCache = IoCManager.Resolve<IResourceCache>();
    }

    public void UpdateState(HashSet<VampireMutationsType> mutationList, VampireMutationsType selectedMutation)
    {
        _possibleMutations = mutationList;
        _selectedId = selectedMutation;
        UpdateGrid();
    }

    private void UpdateGrid()
    {
        ClearGrid();

        var group = new ButtonGroup();

        foreach (var Mutation in _possibleMutations)
        {
            //if (!_prototypeManager.TryIndex("NormalBlobTile", out EntityPrototype? proto))
            //    continue;

            const string rsiPath = "/Textures/_Pirate/Interface/Actions/actions_vampire.rsi";
            var textureState = Mutation switch
            {
                VampireMutationsType.None => "deathsembrace",
                VampireMutationsType.Hemomancer => "hemomancer",
                VampireMutationsType.Umbrae => "umbrae",
                VampireMutationsType.Gargantua => "gargantua",
                VampireMutationsType.Dantalion => "dantalion",
                VampireMutationsType.Bestia => "bestia",
                VampireMutationsType.Sire => "sire",
                _ => "deathsembrace"
            };

            var button = new Button
            {
                MinSize = new Vector2(64, 64),
                HorizontalExpand = true,
                Group = group,
                StyleClasses = {StyleBase.ButtonSquare},
                ToggleMode = true,
                Pressed = _selectedId == Mutation,
                ToolTip = Loc.GetString($"vampire-mutation-{Mutation.ToString().ToLower()}-info"),
                TooltipDelay = 0.01f,
            };
            button.OnPressed += _ => OnIdSelected?.Invoke(Mutation);
            Grid.AddChild(button);

            var rsi = _resourceCache.GetResource<RSIResource>(rsiPath).RSI;
            if (!rsi.TryGetState(textureState, out var rsiState)
                && !rsi.TryGetState("deathsembrace", out rsiState))
            {
                continue;
            }

            var texture = rsiState.Frame0;
            button.AddChild(new TextureRect
            {
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                Texture = texture,
            });
        }
    }

    private void ClearGrid()
    {
        Grid.RemoveAllChildren();
    }
}
