// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Client.Viewport;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.Utility;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using System.Collections.Generic;
using System.IO;
using System.Numerics;

namespace Content.Client._Pirate.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class PhotoCameraWindow : FancyWindow
{
    private const int PreviewSize = 8;
    private const int PreviewSampleSize = 32;

    [Dependency] private readonly IResourceCache _cache = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly PhotoCaptureFilterSystem _photoCaptureFilter;
    private readonly HashSet<IDisposable> _pendingSuppressionScopes = new();

    public Vector2 MoveInput = Vector2.Zero;
    public float ZoomInput = 0;

    public event Action? OnTakeImageAttempt;
    public ScalingViewport CameraViewport => CameraView;

    public PhotoCameraWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _photoCaptureFilter = _entity.System<PhotoCaptureFilterSystem>();

        CameraView.ViewportSize = new Vector2i(250, 250);

        PhotoButton.BaseTexture = new SpriteSpecifier.Texture(new("/Textures/_Pirate/Interface/Misc/Photo/button_base.png"));
        PhotoButton.PointedTexture = new SpriteSpecifier.Texture(new("/Textures/_Pirate/Interface/Misc/Photo/button_highlight.png"));
        PhotoButton.PressedTexture = new SpriteSpecifier.Texture(new("/Textures/_Pirate/Interface/Misc/Photo/button_pressed.png"));
        PhotoButton.ShowBase();

        if (_cache.TryGetResource("/Audio/Items/Stamp/automatic_stamp.ogg", out AudioResource? resource))
            PhotoButton.ClickSound = resource;

        PhotoButton.OnPressed += args =>
        {
            OnTakeImageAttempt?.Invoke();
        };
    }

    //region Control
    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);

        ZoomInput = -args.Delta.Y;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        HandleMoveKey(args.Function, 1);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        HandleMoveKey(args.Function, -1);
    }

    private void HandleMoveKey(BoundKeyFunction function, float delta)
    {
        if (function == EngineKeyFunctions.MoveUp)
            MoveInput.Y = MoveInput.Y + delta;
        else if (function == EngineKeyFunctions.MoveDown)
            MoveInput.Y = MoveInput.Y - delta;
        else if (function == EngineKeyFunctions.MoveRight)
            MoveInput.X = MoveInput.X + delta;
        else if (function == EngineKeyFunctions.MoveLeft)
            MoveInput.X = MoveInput.X - delta;
    }
    //endregion Control

    public void UpdateState(IEye? eye, bool hasPaper)
    {
        SetCameraView(eye);

        PaperIndicator.TexturePath = "/Textures/_Pirate/Interface/Misc/Photo/paper_" + (hasPaper ? "on.png" : "off.png");
    }

    private void SetCameraView(IEye? eye)
    {
        CameraView.Eye = eye;
    }

    public void RenderImage(Action<byte[], byte[]?> callback)
    {
        var filterScope = _photoCaptureFilter.BeginPhotoCaptureSuppression(CameraView.Eye);
        _pendingSuppressionScopes.Add(filterScope);

        CameraView.Screenshot(image =>
        {
            byte[] fullImageBytes;
            byte[]? previewBytes = null;

            try
            {
                try
                {
                    using var data = new MemoryStream();
                    image.SaveAsPng(data);
                    fullImageBytes = data.ToArray();
                }
                catch (System.Exception ex)
                {
                    Logger.ErrorS("photo-camera", $"Failed to write screenshot PNG via image.SaveAsPng while building fullImageBytes in {nameof(PhotoCameraWindow)}: {ex}");
                    return;
                }

                try
                {
                    // Build a miniature preview from the captured full image.
                    var stageOne = DownscaleBox(image.GetPixelSpan(), image.Width, image.Height, PreviewSampleSize, PreviewSampleSize);
                    var stageTwo = DownscaleBox(stageOne, PreviewSampleSize, PreviewSampleSize, PreviewSize, PreviewSize);
                    using var miniature = new Image<Rgba32>(PreviewSize, PreviewSize);
                    stageTwo.CopyTo(miniature.GetPixelSpan());

                    using var previewStream = new MemoryStream();
                    miniature.SaveAsPng(previewStream);
                    previewBytes = previewStream.ToArray();
                }
                catch (System.Exception ex)
                {
                    previewBytes = null;
                    Logger.WarningS("photo-camera",
                        $"Failed to generate previewBytes in {nameof(PhotoCameraWindow)} (DownscaleBox/miniature.SaveAsPng). " +
                        $"Continuing with fullImageBytes only; possible cause is invalid image data or PNG encoding failure. {ex}");
                }

                callback(fullImageBytes, previewBytes);
            }
            finally
            {
                filterScope.Dispose();
                _pendingSuppressionScopes.Remove(filterScope);
            }
        });
    }

    private static Rgba32[] DownscaleBox(ReadOnlySpan<Rgba32> source, int sourceWidth, int sourceHeight, int targetWidth, int targetHeight)
    {
        if (targetWidth <= 0)
            throw new System.ArgumentOutOfRangeException(nameof(targetWidth), targetWidth, "Target width must be greater than zero.");

        if (targetHeight <= 0)
            throw new System.ArgumentOutOfRangeException(nameof(targetHeight), targetHeight, "Target height must be greater than zero.");

        if (sourceWidth <= 0)
            throw new System.ArgumentOutOfRangeException(nameof(sourceWidth), sourceWidth, "Source width must be greater than zero.");

        if (sourceHeight <= 0)
            throw new System.ArgumentOutOfRangeException(nameof(sourceHeight), sourceHeight, "Source height must be greater than zero.");

        var result = new Rgba32[targetWidth * targetHeight];

        for (var y = 0; y < targetHeight; y++)
        {
            var sourceY0 = y * sourceHeight / targetHeight;
            var sourceY1 = (y + 1) * sourceHeight / targetHeight;
            if (sourceY1 <= sourceY0)
                sourceY1 = sourceY0 + 1;

            for (var x = 0; x < targetWidth; x++)
            {
                var sourceX0 = x * sourceWidth / targetWidth;
                var sourceX1 = (x + 1) * sourceWidth / targetWidth;
                if (sourceX1 <= sourceX0)
                    sourceX1 = sourceX0 + 1;

                var sumR = 0;
                var sumG = 0;
                var sumB = 0;
                var sumA = 0;
                var count = 0;

                for (var sourceY = sourceY0; sourceY < sourceY1; sourceY++)
                {
                    var rowOffset = sourceY * sourceWidth;
                    for (var sourceX = sourceX0; sourceX < sourceX1; sourceX++)
                    {
                        var pixel = source[rowOffset + sourceX];
                        sumR += pixel.R;
                        sumG += pixel.G;
                        sumB += pixel.B;
                        sumA += pixel.A;
                        count++;
                    }
                }

                if (count <= 0)
                {
                    result[y * targetWidth + x] = default;
                    continue;
                }

                result[y * targetWidth + x] = new Rgba32(
                    (byte) (sumR / count),
                    (byte) (sumG / count),
                    (byte) (sumB / count),
                    (byte) (sumA / count));
            }
        }

        return result;
    }

    public void OnDispose()
    {
        foreach (var scope in _pendingSuppressionScopes)
        {
            scope.Dispose();
        }

        _pendingSuppressionScopes.Clear();

        // Dispose sound source
        PhotoButton.ClickSound = null;
    }
}
